list = [{
        order: "",
        keywords: "Game Art游戏",
        year: "",
        title: "",
        url: "",
        author: "",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 1,
        keywords: "Game Art游戏",
        year: "2020年12月22日",
        title: "到美术馆打电子游戏？当代艺术为什么要关注“游戏的人”",
        url: "https://mp.weixin.qq.com/s/evcBE6RL3FENfM6ixj8uqQ",
        author: "何佩莲",
        info: {
            A: "“游戏的人”展",
            B: "策展",
            C: "游戏文化、电子游戏、技术资源、公共游戏空间、陆扬、商业跨界、失败者、郑国谷、曹斐",
            D: "上海",
            E: "明当代美术馆",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 2,
        keywords: "Game Art游戏",
        year: "2020/7/27",
        title: "在世界的游戏中，谁是游戏的人",
        url: "https://mp.weixin.qq.com/s/YxNSIzHoxe86VUXp7yyYeg",
        author: "陈旻",
        info: {
            A: "“游戏社会：狼、猞猁和蚁群”Hyundai Blue Prize 2019年获奖展",
            B: "策展",
            C: "智能终端时代、动物行为、互联网空间、非线性叙事展览、虚拟角色、游戏规则、社会关联、交互场所、集体游戏、共同语言",
            D: "北京",
            E: "现代汽车文化中心",
            F: "陈旻、张业鸿",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 3,
        keywords: "Game Art游戏",
        year: "2020/10/28",
        title: "人机接口——逐渐失控的美丽新世界",
        url: "https://mp.weixin.qq.com/s/V49Uy5K_76l1t0JpKOKKWg",
        author: "",
        info: {
            A: "“人机接口——逐渐失控的美丽新世界”群展",
            B: "策展，新媒体",
            C: "火星、人类、线上展览、虫洞、中央美术学院、游戏式交互体验、非物质性策展",
            D: "线上",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 4,
        keywords: "Game Art游戏",
        year: "2020/3/6",
        title: "属于新世代的线上艺术体验是什么？X美术馆有一个大胆玩法",
        url: "https://mp.weixin.qq.com/s/zlcz2FyiwkJI8ggH8UT5sg",
        author: "",
        info: {
            A: "X美术馆",
            B: "机构",
            C: "线上艺术体验、X美术馆、黄勖夫、交互式虚拟空间、游戏性、强家栋、实体美术馆的延伸、适应新习惯",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 5,
        keywords: "Game Art游戏",
        year: "2020/7/9",
        title: "人工智能艺术 + 游戏艺术 | 龙星如×陈旻×张业鸿",
        url: "https://mp.weixin.qq.com/s/EEZkxQoLOmiIa8jd9g0bFQ",
        author: "龙星如、陈旻、张业鸿",
        info: {
            A: "",
            B: "批评",
            C: "人工智能艺术、游戏艺术、机械、泛智能、机器生命、算法黑箱、科技神话、共同性关系构建、虚拟现实",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 6,
        keywords: "Game Art游戏",
        year: "2020/5/1",
        title: "抗疫消消乐",
        url: "https://mp.weixin.qq.com/s/4jGdAXEXspde_nNsKHjZXA",
        author: "黄一山",
        info: {
            A: "",
            B: "新媒体",
            C: "黄一山、孟尧、消消乐、emoji版权问题、画刊封面计划、游戏制作、互动视频、记忆共享",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 7,
        keywords: "Game Art游戏",
        year: "2020/5/15",
        title: "田晓磊 〈我要为你跳支舞〉",
        url: "https://mp.weixin.qq.com/s/QtRA3rFL_djdlcAlzORAYw",
        author: "王芷子、田晓磊",
        info: {
            A: "林中路｜实验影像工作室",
            B: "新媒体",
            C: "田晓磊、“我要为你跳支舞”、赛伯格形象、VR、虚拟游戏、未来元素品牌",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 8,
        keywords: "Game Art游戏",
        year: "2020/6/18",
        title: "游戏社会的狼、猞猁和蚁群，你想到了社交中的谁？",
        url: "https://mp.weixin.qq.com/s/KVpIJeabfoIsxjxClXqO1w",
        author: "张曦元",
        info: {
            A: "Hyundai Blue Prize 2019获奖展",
            B: "新媒体",
            C: "游戏、陈旻、张业鸿、社交智能、泛智能、狼、信息高速公路、猞猁、原子化、孤独、蚁群、集体协作、疫情",
            D: "北京",
            E: "现代汽车文化中心",
            F: "陈旻、张业鸿",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 9,
        keywords: "Game Art游戏",
        year: "2020/9/27",
        title: "2020亚洲数字艺术展开幕，中国数字艺术大爆发已来临",
        url: "https://mp.weixin.qq.com/s/MjvP7BTlSSMxFT5qWd3Caw",
        author: "任艺时",
        info: {
            A: "亚洲数字艺术展",
            B: "新媒体，策展",
            C: "2020亚洲数字艺术展、亚洲文明对话大会、数字技术、世界处理器、可视化、陈抱阳、展览即游戏、线上展厅",
            D: "北京",
            E: "时代美术馆",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 10,
        keywords: "Game Art游戏",
        year: "2020/6/17",
        title: "当我们遁身游戏世界，看到了什么？",
        url: "https://mp.weixin.qq.com/s/eOfZJaVovyeNCy3izkQ44g",
        author: "龙星如、陆明龙、Dhruv Jani等",
        info: {
            A: "",
            B: "影像",
            C: "陆明龙、数字游戏、超现实主义、虚拟现实、全生产链、叙事能力、游戏媒介语言、引擎技术、历史真实性合法化、游戏逻辑、人工智能、生命科学、生命感",
            D: "北京",
            E: "时代美术馆",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 11,
        keywords: "Game Art游戏",
        year: "2020/10/15",
        title: "CAC Presents | 游戏、数字化人与虚拟偶像",
        url: "https://mp.weixin.qq.com/s/BTOzL2mV4CrHPXQgYP2hEA",
        author: "",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 12,
        keywords: "Game Art游戏",
        year: "2020/11/5",
        title: "无面之眼 I：数字幻想",
        url: "https://mp.weixin.qq.com/s/Dz9C-icSYiMh07_ZQj5EHw",
        author: "",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 13,
        keywords: "Game Art游戏",
        year: "2020/11/6",
        title: "无面之眼 II：新兴现实",
        url: "https://mp.weixin.qq.com/s/AMvK3YX8OsHUvVwaYZfy4w",
        author: "",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 14,
        keywords: "Game Art游戏",
        year: "2020/11/9",
        title: "CAC Presents | 陆扬：妄想世界 + 陸揚地獄",
        url: "https://mp.weixin.qq.com/s/WvZCWbrGHqb0GeBkMTXKkQ",
        author: "",
        info: {
            A: "陆扬：妄想世界（线上表演直播）",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 15,
        keywords: "Game Art游戏",
        year: "2020/8/21",
        title: "郑源 “媒介超忆景观”",
        url: "https://mp.weixin.qq.com/s/ovBP321fKtYA9_YiHo1RKQ",
        author: "郑源、王姝曼",
        info: {
            A: "",
            B: "新媒体",
            C: "郑源、媒介超忆景观、斯诺克、文字、游戏、网络、航空、摄影、连续性、艺术在场性、文化资源",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 16,
        keywords: "Game Art游戏",
        year: "2020/7/10",
        title: "陆扬：我决定舍弃肉身， 重新投胎于虚拟世界",
        url: "https://mp.weixin.qq.com/s/v79KwA-BACDHBiNa8FLC3w",
        author: "上海外滩美术馆、陆扬",
        info: {
            A: "",
            B: "影像",
            C: "陆扬、数字技术、虚拟角色、数字人、面部识别技术、人体改造、真人实时替代系统",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 17,
        keywords: "Game Art游戏",
        year: "2021/1/29",
        title: "文化的涌浪到运筹的回路：边界、区域，及变迁中的劳动",
        url: "https://mp.weixin.qq.com/s/PUk1MtSOGI74gbvNz8zPow",
        author: "Brett Neilson",
        info: {
            A: "Cargonauts, Creative Commons Licence 4.0, 2015",
            B: "新媒体",
            C: "From Flows of Culture to the Circuits of Logistics: borders, regions, labour in transit",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 18,
        keywords: "Game Art游戏",
        year: "2018/1/13",
        title: "最好没有“严肃游戏”",
        url: "https://indienova.com/indie-game-news/its-better-if-there-is-no-serious-game/",
        author: "叶梓涛",
        info: {
            A: "",
            B: "游戏与人文",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 19,
        keywords: "Game Art游戏",
        year: "2018/9/7",
        title: "殊途同归的新媒体艺术与电子游戏",
        url: "https://indienova.com/indie-game-news/its-better-if-there-is-no-serious-game/",
        author: "叶梓涛",
        info: {
            A: "",
            B: "游戏与人文",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 20,
        keywords: "Game Art游戏",
        year: "2018/6/13",
        title: "重思虚拟现实与艺术",
        url: "https://indienova.com/indie-game-news/vr-and-art-rethinking/",
        author: "叶梓涛",
        info: {
            A: "",
            B: "游戏与人文",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 21,
        keywords: "Game Art游戏",
        year: "2020/12/17",
        title: "中国当代艺术场域中的电子游戏｜落日间",
        url: "https://indienova.com/indie-game-news/the-video-game-in-chinese-contemporary-art-field/",
        author: "叶梓涛",
        info: {
            A: "",
            B: "游戏与人文",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 22,
        keywords: "Game Art游戏",
        year: "2019/11/20",
        title: "Ailleurs 别处的游戏设计 第一辑",
        url: "https://indienova.com/indie-game-development/ailleurs-1/",
        author: "叶梓涛",
        info: {
            A: "",
            B: "游戏与人文",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 23,
        keywords: "Game Art游戏",
        year: "2016/8/15",
        title: "叙事的玩法：游戏叙事研究梳理 #1：研究背景",
        url: "https://indienova.com/indie-game-development/game-narrative-1/",
        author: "ayame",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 24,
        keywords: "Game Art游戏",
        year: "2019/8/12",
        title: "游戏研究相关书籍目录",
        url: "https://indienova.com/indie-game-news/personal-game-studies-catalog/",
        author: "叶梓涛",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 25,
        keywords: "Game Art游戏",
        year: "",
        title: "知乎专栏游戏与人文",
        url: "https://zhuanlan.zhihu.com/c_1137656202019459072",
        author: "叶梓涛",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 26,
        keywords: "Game Art游戏",
        year: "2017/9/13",
        title: "游戏理论：哈伦·法罗基（Harun Farocki）最后的项目 | ARTFORUM杂志",
        url: "https://mp.weixin.qq.com/s?__biz=MzA3NjUyNzAxNg==&mid=2649755899&idx=1&sn=cc35cbd9b0e3b6418d80624bf573c764&scene=21",
        author: " Adam Jasper",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: "",
        keywords: "Art Fairs艺博会",
        year: "",
        title: "",
        url: "",
        author: "",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 27,
        keywords: "Art Fairs艺博会",
        year: "2020/5/30",
        title: "画廊周北京2020，逆境中的重启与复苏",
        url: "https://mp.weixin.qq.com/s/5ZHR-9keyE7GftP74OyOog",
        author: "VIVIAN、王一妃",
        info: {
            A: "画廊周北京",
            B: "博览会",
            C: "画廊周北京2020、活跃行业氛围、最佳展览奖、新势力单元、线下转为线上、挑战与机遇、自媒体宣传、公共单元直播、传媒社会",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 28,
        keywords: "Art Fairs艺博会",
        year: "2020/5/1",
        title: "台北当代全新数字计划：要替代的不是一场艺博会！",
        url: "https://mp.weixin.qq.com/s/bekpLIBndqxcD7DrwlOMzg",
        author: "罗书银、岳鸿飞、Christopher Taylor",
        info: {
            A: "台北当代艺博会",
            B: "博览会",
            C: "台北当代、艺术平台Ocula、线上艺博会、99家画廊、免费、疫情",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 29,
        keywords: "Art Fairs艺博会",
        year: "2020/3/29",
        title: "滕丽：线上艺博会 更新世界艺术格局的机会？",
        url: "https://mp.weixin.qq.com/s/Bmpi1h5GPKZ4b6hz4D3uKQ",
        author: "罗书银、滕丽",
        info: {
            A: "艺术厦门",
            B: "博览会",
            C: "艺术品线上交易、艺术厦门、线上博览会、推广方式、刚需人群、数据化管理分析、价格公开透明化、艺术市场",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 30,
        keywords: "Art Fairs艺博会",
        year: "2020/3/18",
        title: "无奈的新时代？2020香港巴塞尔线上开幕",
        url: "https://mp.weixin.qq.com/s/IkVcIipIPsuk2kKKUs7FpA",
        author: "王家北",
        info: {
            A: "巴塞尔线上",
            B: "博览会",
            C: "香港巴塞尔、线上开幕、巨大作品、摆脱空间限制、现实氛围、身份确认、市场交易、在场、区块链、艺术电商化、终结与再生",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 31,
        keywords: "Art Fairs艺博会",
        year: "2020/3/14",
        title: "作品总价值超2.5亿美元，即将开幕的巴塞尔线上展厅有什么值得期待？",
        url: "https://mp.weixin.qq.com/s/0YKvt4_HVqrAUCd8cBex2g",
        author: "Tim Schneider",
        info: {
            A: "巴塞尔线上",
            B: "博览会",
            C: "2.5亿美元、巴塞尔线上展厅、透明度、精确价格",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 32,
        keywords: "Art Fairs艺博会",
        year: "2020/3/18",
        title: "线上艺博会的终极提问：会看，但你会买吗？",
        url: "https://mp.weixin.qq.com/s/Hku1HO8cppbWAWPGasBB1w",
        author: "罗书银",
        info: {
            A: "艺术北京、巴塞尔、北京当代",
            B: "博览会，媒介",
            C: "线上艺博会、香港巴塞尔网上展厅、线上交易、艺术品电子商务、消费级艺术品、艺术北京、二级市场成熟遗嘱作品、北京当代、线上线下配合、疫情、实时互动、Zoom Meeting、线上导览、模拟展示图、画廊经营模式革命、潮流艺术",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 33,
        keywords: "Art Fairs艺博会",
        year: "2020/3/19",
        title: "巴塞尔首次网上展厅上线，艺博会与画廊寻求线上交易新出路",
        url: "https://mp.weixin.qq.com/s/44QbZOd_GtSTP0bo_fJVWA",
        author: "林佳珣、孟宪晖",
        info: {
            A: "巴塞尔",
            B: "博览会，市场",
            C: "巴塞尔艺术展、网上展厅、线上交易、用户体验、技术限制、自我组织导览、蓝筹画廊、时间限制",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 34,
        keywords: "Art Fairs艺博会",
        year: "2020/3/30",
        title: "最全调查！第一个吃螃蟹的线上艺博会战绩如何？",
        url: "https://mp.weixin.qq.com/s/1Mg69XmHSeSrPrTiMiWM6g",
        author: "罗书银",
        info: {
            A: "巴塞尔",
            B: "博览会，市场",
            C: "线上艺博会、首届香港巴塞尔线上展厅、国内画廊差距较大、零成本参展、自身的线上展厅、卓纳画廊“论绘画：线上巴塞尔艺术展”、缓解画廊运营压力、落地展览优势无法取代",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 35,
        keywords: "Art Fairs艺博会",
        year: "2020/4/13",
        title: "新秩序的重整，艺术市场在线化的观察",
        url: "https://mp.weixin.qq.com/s/gp_Lkbp48kl8EOwtokRvvA",
        author: "谢盈盈",
        info: {
            A: "",
            B: "市场",
            C: "新秩序、艺术市场在线化、线下无可替代、客户资料",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 36,
        keywords: "Art Fairs艺博会",
        year: "2020/7/1",
        title: "下一个收藏热点？新媒体艺术如何买卖？",
        url: "https://mp.weixin.qq.com/s/_IxotLEHqauR8D1hPbQaSw",
        author: "韩晗",
        info: {
            A: "",
            B: "新媒体",
            C: "相对概念、免费获取、艺术品作为应用出售、teamLab、艺术体验、可复制性、无数副本、过时、如何收藏",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: "",
        keywords: "线上策展",
        year: "",
        title: "",
        url: "",
        author: "",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 37,
        keywords: "线上策展Online Curation",
        year: "2020/10/9",
        title: "线上策展 第一部分：表现，可变性，物体性",
        url: "https://mp.weixin.qq.com/s/ZSkzV0UW6OebgRsKECK9BA",
        author: "Michael Connor",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 38,
        keywords: "线上策展Online Curation",
        year: "2020/8/12",
        title: "探明所有的墙：林云柯谈流媒体平台与线上策展",
        url: "https://mp.weixin.qq.com/s/EK17H2QJ28tl86jPTQZn5g",
        author: "林云柯",
        info: {
            A: "",
            B: "新媒体，策展",
            C: "线上观影、流媒体平台、数字艺术体制、第四堵墙",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 39,
        keywords: "线上策展Online Curation",
        year: "2020/4/27",
        title: "身体缺席的艺术：陈嘉莹谈近期的线上艺术展览呈现",
        url: "https://mp.weixin.qq.com/s/mTH-ayp8TIuwgW2U0upcuQ",
        author: "陈嘉莹",
        info: {
            A: "",
            B: "批评",
            C: "陈嘉莹、身体缺席、线上艺术展览、疫情、Bank、网络群展“纯美”、数字通信化、香港巴塞尔、策划语境、自我瓦解、链接的要求、网络艺术、互动式作品、常态、体验经济",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 40,
        keywords: "线上策展Online Curation",
        year: "2020/3/19",
        title: "把图片和文字搬到网上就是线上策展吗？",
        url: "https://mp.weixin.qq.com/s/9tvv1vOTswGbmWIdw5niCQ",
        author: "李家丽",
        info: {
            A: "很多",
            B: "策展",
            C: "江苏省美术馆、系列在线展、疫情、陈娅、阿拉里奥画廊、防疫、优势利用、生产反思性话题、策展人身份转换、新媒体规律、内容输出、资本效益、观看体验、300DPI、技术手段、电影导演视角",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 41,
        keywords: "线上策展Online Curation",
        year: "2020/4/10",
        title: "不只线上看图，“云看展”如何突破行业壁垒？",
        url: "https://mp.weixin.qq.com/s/uJ-21AlGupQ9eexTmJQTAw",
        author: "郁婷",
        info: {
            A: "昊美术馆的“How Online Exhibition“Google Art&Culture & British Museim Collection Online木木美术馆线上虚拟展览--“艺术还在：一场闭馆期间的展览”“在线公教”",
            B: "机构",
            C: "云看展、VR美术馆Acute Art VR Museum、行业壁垒、知识生产方式、图文看展、类文献、在线数据库、资讯记录手段、视频直播、内容运作、在线公教、云对谈、在线讲座、断线、VR观展、Google Art & Culture、后网络时代",
            D: "本文讨论了疫情影响向全球美术馆“云看展”的不同方式，并关注是否能进行有效观展的同时实现知识生产。",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 42,
        keywords: "线上策展Online Curation",
        year: "2020/9/21",
        title: "后疫情时代展览的有效性与无效性互观",
        url: "https://mp.weixin.qq.com/s/iEDZLZafvm7OeJJYPAT8ZQ",
        author: "宋文翔",
        info: {
            A: "",
            B: "批评",
            C: "后疫情时代展览、线上展览、线上的有效性、展场的过度社交化和娱乐化、介入社会问题、应景式时展、抗疫主题展览、审美疲劳、公共秩序",
            D: "本文从策展和展览呈现的角度关注“展览何为”和“何为展览”的问题，讨论了疫情影响下展览的有效和无效性，以及后疫情时代策展所需警惕的问题。",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 43,
        keywords: "线上策展Online Curation",
        year: "2020年12月21日",
        title: "当下策展的转向与应对：艺术博物馆的智识机制建构 | “策展在中国”论坛主旨发言",
        url: "https://mp.weixin.qq.com/s/MLAtbpHBikWEl6eBe7y5HQ",
        author: "张子康",
        info: {
            A: "",
            B: "机构，批评",
            C: "艺术博物馆、知识传播中心、大众文化、智识机制建设、线上艺术展、网络依赖性",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 44,
        keywords: "线上策展Online Curation",
        year: "2021/2/24",
        title: "Post-2020|当代艺术跃入线上的“数字元年”，正在编码的全球艺术界数字活动地图",
        url: "https://mp.weixin.qq.com/s/Z60-elrBDDBCHpoWN_xZJg",
        author: "",
        info: {
            A: "曹斐/Trigger/Clubhouse/赤屏/艺术家影院/数字化博物馆",
            B: "机构，批评",
            C: "艺术博物馆、知识传播中心、大众文化、智识机制建设、线上艺术展、网络依赖性",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: "",
        keywords: "History of Digital Art数字艺术历史",
        year: "",
        title: "",
        url: "",
        author: "",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 45,
        keywords: "History of Digital Art数字艺术历史",
        year: "2020/1/15",
        title: "过去十年，科技如何影响了艺术的模样？",
        url: "https://mp.weixin.qq.com/s/xMzlkhf1Y3bQ3j0-bt0aiA",
        author: "任艺时",
        info: {
            A: "",
            B: "新媒体",
            C: "科技、社交媒体、4G网络、耿雪、蓝牙技术、张鼎、脑科学、神经科学、费俊、冯梦波、语音识别、基因工程、邓悦君、李山",
            D: "本文选取了过去十年科技领域的几项技术突破与产品创新作为切入点，结合对几名艺术家的访谈与对展览机构过去项目，回顾了过去十年“科技与艺术”这一命题的发展情况。",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 46,
        keywords: "History of Digital Art数字艺术历史",
        year: "2020/3/11",
        title: "艺术世界被不断推进，科技对艺术作了什么？",
        url: "https://mp.weixin.qq.com/s/os1TDw8IrCqwn4S26EsvkA",
        author: "推 巴塞尔",
        info: {
            A: "",
            B: "新媒体",
            C: "科技、艺术、巴塞尔艺术展50周年、线上展厅、数字艺术、计算机、波普艺术、虚拟现实（VR）、HTC Vive Art、沉浸式、谷歌艺术中心、美感经验",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 47,
        keywords: "History of Digital Art数字艺术历史",
        year: "2020/11/8",
        title: "受控随机：数字艺术的早起早期探索",
        url: "https://mp.weixin.qq.com/s/BCq7nMnKhJAQ7UXUDvFeqw",
        author: "",
        info: {
            A: "",
            B: "新媒体",
            C: "科技、艺术、巴塞尔艺术展50周年、线上展厅、数字艺术、计算机、波普艺术、虚拟现实（VR）、HTC Vive Art、沉浸式、谷歌艺术中心、美感经验",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 48,
        keywords: "History of Digital Art数字艺术历史",
        year: "2020年12日7日",
        title: "CAC·阅读 | nettime: 网络艺术（net.art）之起源",
        url: "https://mp.weixin.qq.com/s/yf5t_s-O2rlZ0nLbXxLQqg",
        author: "阿列克谢·舒尔金",
        info: {
            A: "",
            B: "新媒体",
            C: "科技、艺术、巴塞尔艺术展50周年、线上展厅、数字艺术、计算机、波普艺术、虚拟现实（VR）、HTC Vive Art、沉浸式、谷歌艺术中心、美感经验",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 49,
        keywords: "History of Digital Art数字艺术历史",
        year: "1905/7/12",
        title: "We=Link | 早期互联网艺术 I：浏览器艺术与网络艺术美学",
        url: "https://mp.weixin.qq.com/s/euaJ-8287SoxDcfPvbR3Pg",
        author: "",
        info: {
            A: "",
            B: "新媒体",
            C: "科技、艺术、巴塞尔艺术展50周年、线上展厅、数字艺术、计算机、波普艺术、虚拟现实（VR）、HTC Vive Art、沉浸式、谷歌艺术中心、美感经验",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 50,
        keywords: "History of Digital Art数字艺术历史",
        year: "1905/7/12",
        title: "We=Link | 早期网络艺术II：ASCII转码艺术",
        url: "https://mp.weixin.qq.com/s/4hFaZZ5Hj0aWgLZMK5Yz_w",
        author: "",
        info: {
            A: "",
            B: "新媒体",
            C: "科技、艺术、巴塞尔艺术展50周年、线上展厅、数字艺术、计算机、波普艺术、虚拟现实（VR）、HTC Vive Art、沉浸式、谷歌艺术中心、美感经验",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
];