list = [{
	type: 'Art Gallery‘s NFT release',
	year: '2022/2/1',
	name: 'Echoes',
	person: 'Peter Wu+',
	info: {
		A: '画廊线上展览Commercial Gallery‘s Online Exhibition/NFT release',
		B: '2022/2/1',
		C: '2022/05/01',
		D: 'Echoes',
		E: 'American Artist | Lukas Avendaño, EYIBRA (Abraham Brody), NNUX (Ana Lopez), and Oswaldo Erreve Jaqueline Kiyomi Gork and Rhett LaRue | Lawerence Lek | Jen Liu | Ronald Rael and Virginia San Fratello | Sarah Rara',
		F: "e-gallery website; blockchain",
		G: 'EPOCH x LACMA ART + TECHNOLOGY LAB',
		H: '',
		I: '',
		J: 'Peter Wu+',
		K: '',
		L: 'https://epoch.gallery/phantomlimb/',
		M: 'https://lawrencelek.com/',
		N: 'inspired by and modeled after the demolition of the LACMA Ahmanson building.',
		O: '',
		P: 'Lawrence Lek 陆明龙',
		Q: ['./images/1.png']
	},
	color: '#fe0000'
},
{
	type: '画廊NFT发行Gallery‘s NFT Release',
	year: '2022/1/22',
	name: 'A map is also a score',
	person: 'art block',
	info: {
		A: '画廊NFT发行Gallery‘s NFT Release',
		B: '2022/1/22',
		C: '',
		D: 'A map is also a score',
		E: 'John Provencher',
		F: "artist website;blockchain",
		G: 'art block',
		H: '',
		I: '',
		J: '',
		K: '',
		L: 'https://a-map-is-a-score.com/',
		M: '',
		N: 'generative art;Blockchain participants',
		O: '',
		P: '',
		Q: ['./images/2.png']
	},
	color: '#ff0046'
},
{
	type: '艺术家（组合）NFT发行Artist/Group NFT Release',
	year: '2022/1/15',
	name: 'store; Bert Krak (collaborative artist)',
	person: 'art block',
	info: {
		A: '艺术家（组合）NFT发行Artist/Group NFT Release',
		B: '2022/1/15',
		C: '',
		D: 'store; Bert Krak (collaborative artist)',
		E: 'frankie; The Seven Letters',
		F: "artist website;blockchain",
		G: 'STORE_CORP',
		H: '',
		I: '',
		J: 'art block',
		K: '',
		L: 'https://sto.re/',
		M: 'Opensea; Twitter;',
		N: 'gamification; blockchain participants',
		O: '',
		P: '',
		Q: ['./images/3.jpeg']
	},
	color: '#fe0086'
},
{
	type: '线上档案Digital Archive',
	year: '2022/1/1',
	name: 'Surfacing Women in Smithsonian History',
	person: 'Elizabeth Harmon, Lynn Cherny',
	info: {
		A: '线上档案Digital Archive',
		B: '2022/1/1',
		C: '',
		D: 'Surfacing Women in Smithsonian History',
		E: 'By Dr. Elizabeth Harmon, Digital Curator, Smithsonian Libraries and Archives & Dr. Lynn Cherny, Google Arts & Culture Lab',
		F: "Smithsonian Libraries and Archives",
		G: 'Smithsonian Libraries and Archives',
		H: 'Google Arts & Culture Lab',
		I: 'Smithsonian Libraries and Archives',
		J: 'Elizabeth Harmon, Lynn Cherny',
		K: '',
		L: 'https://experiments.withgoogle.com/women-in-smithsonian-history',
		M: '',
		N: 'Developing machine learning tools to help Smithsonian curators uncover the history and contributions of women in science',
		O: '',
		P: 'interactive documentary/online exhibition with machine learning',
		Q: ['./images/4.png']
	},
	color: '#f400b8'
},
{
	type: '艺术家/组合线上项目Artist/Group Online Project',
	year: '2021/12/4',
	name: 'Illusion',
	person: 'Arianna Zampini',
	info: {
		A: '艺术家/组合线上项目Artist/Group Online Project',
		B: '2021/12/4',
		C: '2022/02/05',
		D: 'Illusion',
		E: 'Arianna Zampini',
		F: "web/ mobile app",
		G: 'The Widget Art Gallery',
		H: '',
		I: '',
		J: 'Arianna Zampini',
		K: 'http://the-widget-art-gallery.blogspot.com/',
		L: 'http://www.chiarapassa.it/wag/',
		M: '',
		N: '“Illusion” is a gif. ',
		O: '',
		P: '有50個展覽在裡面！（there are 50 exhibitions in the WAG, but I only documented the current exhibition, will fill them in soon) ',
		Q: ['./images/5.png']
	},
	color: '#da00ff'
},
{
	type: '研究机构线上展览Research Institute Online Exhibition',
	year: '2021/12/1',
	name: '图像的格列佛化：Art of Science 线上展览',
	person: 'WEHI',
	info: {
		A: '研究机构线上展览Research Institute Online Exhibition',
		B: '2021/12/1',
		C: '',
		D: '图像的格列佛化：Art of Science 线上展览',
		E: '',
		F: "institution's website",
		G: 'WEHI（The Walter and Eliza Hall Institute of Medical Research）',
		H: '',
		I: '',
		J: 'WEHI',
		K: '',
		L: 'https://wehi.spacesplusprojects.co/',
		M: '',
		N: 'Online archive',
		O: '',
		P: '',
		Q: ['./images/6.webp']
	},
	color: '#a41cff'
},
{
	type: '画廊NFT发行Gallery‘s NFT Release',
	year: '2021/11/30',
	name: 'GRAPH',
	person: 'Casey Reas',
	info: {
		A: '画廊NFT发行Gallery‘s NFT Release',
		B: '2021/11/30',
		C: '',
		D: 'GRAPH',
		E: 'Aleksandra Jovanić; Julien Gachadoat; Tyler Hobbs; Licia He Iskra Velitchkova; James Merrill; ',
		F: "美术馆官方网站 Gallery's official Website",
		G: 'Feral File',
		H: 'Feral File',
		I: 'Feral File',
		J: 'Casey Reas',
		K: '',
		L: 'https://feralfile.com/exhibitions/graph-eg6',
		M: '',
		N: "Feral File is the most curated (in a traditional way) NFT gallery I have seen so far. It's like an online magazine. Their curator's articles are really good and the digital art they chose are in high quality.",
		O: '',
		P: '',
		Q: ['./images/7.png']
	},
	color: '#7050ff'
},
{
	type: '画廊线上展览Commercial Gallery‘s Online Exhibition/NFT release',
	year: '2021/10/24',
	name: 'Phantom Limb',
	person: 'Peter Wu+',
	info: {
		A: '画廊线上展览Commercial Gallery‘s Online Exhibition/NFT release',
		B: '2021/10/24',
		C: '2022/01/08',
		D: 'Phantom Limb',
		E: 'Mohamed Bourouissa | Eli Cortiñas | Cayetano Ferrer | Malisa Humphrey | Kang Seung Lee | Patrick Martinez | Shizu Saldamando | Clarissa Tossin | Mario Ybarra Jr.',
		F: "e-gallery website; blockchain",
		G: 'Epoch Gallery ',
		H: '',
		I: '',
		J: 'Peter Wu+',
		K: '',
		L: 'https://epoch.gallery/phantomlimb/',
		M: '',
		N: 'inspired by and modeled after the demolition of the LACMA Ahmanson building.',
		O: '',
		P: '',
		Q: ['./images/8.png']
	},
	color: '#0068ff'
},
{
	type: '艺术书展Virtual Book Fair',
	year: '2021/10/22',
	name: '2021 Tokyo Virtual Art Book Fair',
	person: 'Tokyo Virtual Art Book Fair',
	info: {
		A: '艺术书展Virtual Book Fair',
		B: '2021/10/22',
		C: '2021/10/31',
		D: '2021 Tokyo Virtual Art Book Fair',
		E: "A:  Akane komatsu ako doi ALBATRO DESIGN Align D - AA Allied Forces Press Amenyan Anyway Press Aperture Brought Me Here x Palmhouse applause apres midi ART BOOK CO-OP Supported by FUJIFILM Business Innovation Corp. Art Byte Critique ART PAPER EDITIONS Asami TOGAWA｜Togawa-shoten ASIAN_FOOD_DESIGN assignments Atelier HOKO Awkward Ladies Club ayano / fumi",
		F: "Online+Offline Venue",
		G: '2021 Tokyo Virtual Art Book Fair',
		H: 'The Tokyo Art Book Fair/ Special Assistance from the Museum of Contemporary Art Tokyo operated by Tokyo Metropolitan Foundation for History and Culture',
		I: 'Sponsorship provided by inuuniq Co., Ltd., Shiba Park Hotel Support provided under the auspices of the Agency Cultural Affairs’ “ARTS for the future!” program Special assistance provided by ZOZO, Inc, ArtSticker (The Chain Museum Inc.)',
		J: 'Tokyo Virtual Art Book Fair',
		K: 'https://zhuanlan.zhihu.com/p/427058523',
		L: 'htthttps://online2021.tokyoartbookfair.com',
		M: '〒135-0022 4-1-1 Miyoshi, Koto-ku, Tokyo',
		N: 'At this Online Venue, VABF apply their experience in hosting the VABF in 2020 to realize a space where visitors can engage in direct communication with various exhibitors and purchase art publications online; audiences will also be able to find a selection of art books and zines by Online Venue exhibitors for exhibition and sale on our Offline Venue. VABF invite faircomers to enjoy an all-new embodiment of the TABF, one that connects the offline and the online worlds.',
		O: '',
		P: '',
		Q: ['./images/9.png']
	},
	color: '#0077b6'
},
{
	type: '艺术家（组合）NFT发行Artist/Group NFT Release',
	year: '2021/10/14',
	name: 'OG:Crystal',
	person: 'Michael Joo',
	info: {
		A: '艺术家（组合）NFT发行Artist/Group NFT Release',
		B: '2021/10/14',
		C: '',
		D: 'OG:Crystal',
		E: 'Michael Joo(Asomatica), Danil Krivoruchko (Ksoid)',
		F: "artist website;blockchain",
		G: 'snark.art',
		H: '',
		I: '',
		J: 'Michael Joo',
		K: '',
		L: 'https://ogcrystals.com/',
		M: 'sacondary market OpenSea; Rarible',
		N: 'A collaboration between Michael Joo and Danil Krivoruchko, OG:CR transforms static NFTs into a flourishing digital reefscape, where each uniquely individual piece of digital art grows every time it is re-sold.  All 10,301 OG:Crystals will become a direct reflection of both their owner and future transactional  history, creating a visual record of combined digital and organic processes.  Like the living architecture formed by the exo-skeletons of coral polyps, past, present and future coexist, offering a new take on NFTs, value, and the creative process. ',
		O: 'hello@ogcrystal.com',
		P: '',
		Q: ['./images/10.png', './images/10-1.png', './images/10-2.png', './images/10-3.JPG']
	},
	color: '#007b7a'
},
{
	type: '画廊NFT发行Gallery‘s NFT Release',
	year: '2021/10/09',
	name: 'REPLICANTS',
	person: 'Epoch Gallery',
	info: {
		A: '画廊NFT发行Gallery‘s NFT Release',
		B: '2021/10/09',
		C: '2022/01/14',
		D: 'REPLICANTS',
		E: 'Gordon Cheung Galath3a Hung Yu Hao Keiken Katja Novitskova Jennifer West Dr. Woo Qianqian Ye + Tiare Ribeaux Original Music by Konrad Black',
		F: "Epoch Gallery 画廊官方网站",
		G: '',
		H: '',
		I: '',
		J: '',
		K: 'https://epoch.gallery/',
		L: 'https://epoch.gallery/Replicants/index.htm',
		M: '',
		N: 'The exhibition’s framing environment, modeled after Queen’s Road Central in Hong Kong, extends a virtual reproduction of the street and surrounding buildings of Woaw Gallery where REPLICANTS will be featured. ',
		O: '',
		P: ' The REPLICANTS NFT is now available and is released in tandem with its inclusion in, and the opening of,the group exhibition TEKNOLUST: OBJECTOPHILIC FUTURES at Woaw Gallery, Hong Kong',
		Q: ['./images/11.png']
	},
	color: '#237f34'
},
{
	type: '画廊NFT发行Gallery‘s NFT Release',
	year: '2021/10/01',
	name: 'Jiometory No Compute - ジオメトリ ハ ケイサンサレマセン ',
	person: 'art block',
	info: {
		A: '画廊NFT发行Gallery‘s NFT Release',
		B: '2021/10/01',
		C: '',
		D: 'Jiometory No Compute - ジオメトリ ハ ケイサンサレマセン ',
		E: 'Samsy',
		F: "Opensea/Art Block",
		G: 'art block',
		H: '',
		I: '',
		J: 'art block',
		K: 'https://samsy.ninja/nocompute/index.html',
		L: 'https://www.artblocks.io/project/232',
		M: 'https://opensea.io/collection/jiometory-no-compute-ziometori-ha-keisansaremasen',
		N: 'contemplative geometry organism',
		O: '',
		P: '',
		Q: ''
	},
	color: '#008f00'
},
{
	type: '画廊NFT发行Gallery‘s NFT Release',
	year: '2021/10/01',
	name: 'The Old Testament',
	person: 'snark.art; Tommy Hartun',
	info: {
		A: '画廊NFT发行Gallery‘s NFT Release',
		B: '2021/10/1',
		C: '',
		D: 'The Old Testament',
		E: 'Tommy Hartung',
		F: "e-gallery website; blockchain",
		G: 'snark.art',
		H: '',
		I: '',
		J: 'snark.art; Tommy Hartun',
		K: '',
		L: 'https://snark.art/oldtestament/',
		M: '',
		N: '',
		O: '',
		P: '',
		Q: ['./images/13.png']
	},
	color: '#00a700'
},
{
	type: '线上档案Digital Archive',
	year: '2021/10/01',
	name: 'The Mo Amin Archive',
	person: 'Simon Doury, Nicolas Barradeau, Gael Hugo',
	info: {
		A: '线上档案Digital Archive',
		B: '2021/10/1',
		C: '',
		D: 'The Mo Amin Archive',
		E: 'Mo Amin',
		F: "",
		G: '',
		H: '',
		I: '',
		J: 'Simon Doury, Nicolas Barradeau, Gael Hugo',
		K: '',
		L: 'https://artsandculture.google.com/experiment/the-mo-amin-archive/wAEJDXhB5ZAhoA',
		M: '',
		N: '',
		O: '',
		P: '',
		Q: ['./images/14.png']
	},
	color: '#00bc00'
}, {
	type: '画廊NFT发行Gallery‘s NFT Release',
	year: '2021/9/14',
	name: 'spawn by john provencher',
	person: 'art block',
	info: {
		A: '画廊NFT发行Gallery‘s NFT Release',
		B: '2021/9/14',
		C: '',
		D: 'spawn by john provencher',
		E: 'John Provencher',
		F: "Opensea/Art Block",
		G: 'art block',
		H: '',
		I: '',
		J: 'art block',
		K: 'https://opensea.io/collection/spawn-by-john-provencher',
		L: 'https://spawn.club/',
		M: '',
		N: 'spawn is generative nft. 1001 generative spawns were minted on opensea',
		O: '',
		P: '',
		Q: ['./images/15.png']
	},
	color: '#6fb200'
},
{
	type: '画廊NFT发行Gallery‘s NFT Release',
	year: '2021/9/1',
	name: '… all the reporters laughed and took pictures',
	person: 'snark.art; Jack & Leigh Ruby',
	info: {
		A: '画廊NFT发行Gallery‘s NFT Release',
		B: '2021/9/1',
		C: '',
		D: '… all the reporters laughed and took pictures',
		E: 'Jack & Leigh Ruby',
		F: "e-gallery website; blockchain",
		G: 'snark.art',
		H: '',
		I: '',
		J: 'snark.art; Jack & Leigh Ruby',
		K: '',
		L: 'https://snark.art/allthereporters/',
		M: '',
		N: 'is a new ongoing “channelling” performance directed by Jack & Leigh Ruby, first performed at the SPRING/BREAK ART SHOWS in LA and NYC in 2019.',
		O: '',
		P: 'Blockchain Participants',
		Q: ['./images/16.png']
	},
	color: '#a8a500'
},
{
	type: '画廊NFT发行Gallery‘s NFT Release',
	year: '2021/8/10',
	name: 'The Long Cut',
	person: '龙星如',
	info: {
		A: '画廊NFT发行Gallery‘s NFT Release',
		B: '2021/8/10',
		C: '',
		D: 'The Long Cut',
		E: '龙星如 曹澍 郭城 贺子珂 林科；SHI ZHENG',
		F: "FeraFile E-gallery",
		G: '',
		H: '',
		I: 'designed by Studio Above&Below',
		J: 'curated by 龙星如',
		K: '',
		L: 'https://feralfile.com/exhibitions/the-long-cut-bqv',
		M: '',
		N: '展览制作Studio Above&Below is a London based art+technology studio-immersive future speculations through XR, AR, digital art and data.    The exhibition investigates the idea of “shortcuts” and proposes alternatives: the latent, the distant, the ambiguous and the “long cuts”',
		O: '',
		P: '',
		Q: ['./images/17.png']
	},
	color: '#d49200'
},
{
	type: '画廊NFT发行Gallery‘s NFT Release',
	year: '2021/8/1',
	name: 'Burn Before Reading',
	person: 'snark.art; Mr. Fox',
	info: {
		A: '画廊NFT发行Gallery‘s NFT Release',
		B: '2021/8/1',
		C: '',
		D: 'Burn Before Reading',
		E: 'Mr. Fox',
		F: "e-gallery website; blockchain",
		G: 'snark.art',
		H: '',
		I: '',
		J: 'snark.art; Mr. Fox',
		K: '',
		L: 'https://snark.art/fortune-cookies/',
		M: '',
		N: 'Burn Before Reading is an AI-generated crypto-fortune cookie.',
		O: '',
		P: 'Blockchain Participants',
		Q: ['./images/18.png']
	},
	color: '#f57f00'
},
{
	type: '研究机构线上展览Institute‘s Online Exhibition',
	year: '2021/7/21',
	name: '杉浦康平设计档案系统 デザイン・コスモス',
	person: '武蔵野美術大学 美術館・図書館',
	info: {
		A: '研究机构线上展览Research Institute Online Exhibition',
		B: '2021/7/21',
		C: '',
		D: '杉浦康平设计档案系统 デザイン・コスモス',
		E: '杉浦康平',
		F: "institution's website",
		G: '武蔵野美術大学 美術館・図書館が所蔵',
		H: '',
		I: '',
		J: '武蔵野美術大学 美術館・図書館',
		K: '',
		L: 'https://collections.musabi.ac.jp/sugiura_kohei/?continueFlag=1761a0849a0212e85d4f5da499732345',
		M: '',
		N: 'Online archive',
		O: '',
		P: '',
		Q: ['./images/19.jpeg']
	},
	color: '#ff6400'
},
{
	type: '线上研讨会Online Conference',
	year: '2021/7/10',
	name: 'Hybrid by Nature: Human.Machine.Interaction',
	person: 'Sabine Himmelsbach and DooEun Cho',
	info: {
		A: '线上研讨会Online Conference',
		B: '2021/7/10',
		C: '',
		D: 'Hybrid by Nature: Human.Machine.Interaction',
		E: 'Bat-Erdene Batchuluun, h0nh1m (Chris Cheung), Stine Deja, Entangled Others, Exonemo, Mario Klingemann, Vvzela Kook, Loopntale, Sebastian Schmieg, Ruini Shi, Yehwan Song, UBERMORGEN & Atractor, Issei Yamagata',
		F: "institution's website",
		G: 'Goethe-Institut',
		H: '',
		I: '',
		J: 'Sabine Himmelsbach and DooEun Cho',
		K: 'Online Exhibition Start: October 7, 2021, 7.30pm HKT ',
		L: 'https://www.goethe.de/ins/kr/de/ver.cfm?event_id=22353387&wt_sc=hybrid',
		M: 'Online Conference October 7 – 10, 2021 on ZOOM 7.30-9.30pm HKT / 8.30-10.30pm KST / 1.30-3.30pm CET / 7.30-9.30am EDT',
		N: ' Human.Machine.Interaction looks at how machine learning, algorithms and intelligent robots are increasingly determining our everyday lives. The distinction between humans and technical systems is becoming more and more blurred. This transformative development has the potential to dramatically change all aspects of life and society as a whole in the near future. “Posthumanism” and “Transhumanism”, which actively promotes human enhancement, challenge our image of what it means to be human.',
		O: '',
		P: '',
		Q: ['./images/20.png']
	},
	color: '#ff4c00'
},
{
	type: '研究机构线上展览Institute‘s Online Exhibition',
	year: '2021/6/30',
	name: 'StepBackForward.art网络档案',
	person: '李继忠, 沈军',
	info: {
		A: '研究机构线上展览Institute‘s Online Exhibition',
		B: '2021/6/30',
		C: '',
		D: 'StepBackForward.art网络档案',
		E: '参与艺术家与团体：陈翠雯 / 陈庭 / 郑裕林 / 郑虹 / 程新皓 / 郑子峰 / 张紫茵 / 张家桦 / 张绮君 / 张亦勤 / 朱颖琳 / 冯靖岚 / 冯倚天 / 冯以力 / 许芷玮 / 张国梁 / 邝咏君 / Landescape1823/ Florence LAM / 林琬晴 / 刘清华 / 刘菁儿 / 李继忠 / 李佩滢 / 梁望琛 / 李晓巧 / 廖家明 / 刘畅 / 卢韵淇 / 吴咏诗 / 彭景 / 潘美义 / 无码计划 / 强天锴 / 岑倩衡 / 沈军 / 沈军翰 / 谭绰琳 / 谭敏晴 / 邓卓敏 / 邓广燊及袁雅芝 / 曾淑芬 / 王子月 / 屈键晴 / 黄姬雪 / Iris WONG / 黄百亨 / 黄诗慧 / 王昱珊 / 黄慧心 / 徐然 / 杨思嘉 / 叶雯 / 余淑培 / 余荣基 / 张文智 / 郑天依 / 朱建林 / 朱湘',
		F: "独立网站+平面出版",
		G: '独立艺术家团体',
		H: '本项目第一阶段承蒙香港艺术发展局「Arts Go Digital·码平台计划」资助；The first phase of the project issupported by Hong Kong Arts Development Council "Arts Go Digital PlatformScheme".',
		I: '',
		J: '香港艺术家李继忠与艺术工作者沈军',
		K: 'https://mp.weixin.qq.com/s/uVi68J9mrIg2xYlHU6Vj5g',
		L: 'stepbackforward.art',
		M: '网站| Website: stepbackforward.art  电邮 | Email: stepbackforward@gmail.com Facebook：@stepbackforward.art Instagram：@stepbackforward WeChat：stepbackforward',
		N: 'StepBackForward.art是由香港艺术家李继忠与艺术工作者沈军共同发起的网络档案项目，尝试以个体的力量回应全球疫症冲击之下的本地艺术生态，利用自身获得的公共资源帮助同侪及后辈艺术力量，并在时代过渡与人事变迁之时，展开一个适时的艺术档案记录。（来自公众号）北鸥设计',
		O: 'stepbackforward@gmail.com',
		P: "Initiated by Hong Kong artist Lee Kai Chung and researcher Shen Jun, stepbackforward.art is a bottom-up online archive reacting to Hong Kong art ecology under severe impact of socialchanges and global pandemics. The project attempts to redistribute the obtained public resources to emerging art contemporaries, while carrying out timely dialogues and archive in transitional times.  Participating artists andcollectives: Chan Chui Man / Chan Ting / ChangYue Lam / Cheng Hung, Dony / Cheng Xinhao / Cheng Tsz Fung, Jeff / Dorothy Cheung / Janice Cheung / Cheung Yee Kwan, Sonia / Cheung Yick Kan / Chu Wing Lam, Kelly / Fung Ching Laam / Thomas Fung / Fung Yee Lick,Eric / Echo Hui /Weera It Ittiteerarak / Kwong Wing Kwan / Lai Wing Hung / Landescape1823 / Florence Lam / Lam Esther Yuen Ching / Lau Ching Wa, Jess / Lau Ching Yee, Cathleen / Lee Kai Chung / Lee Pui Ying, Hiya / Leung Mong Sum, Joseph / LiXiaoqiao / Liao Jiaming / Liu Chang / Lo Wan Ki / Ng Wing Sze / Peng Jing",
		Q: ['./images/21.webp']
	},
	color: '#ff3700'
},
{
	type: '美术馆线上展Art Museum Online Exhibition',
	year: '2021/6/28',
	name: '线悬世界 World on a Wire',
	person: 'Michael Connor 陈嘉莹',
	info: {
		A: '美术馆线上展 Art Museum Online Exhibition',
		B: '2021/6/28',
		C: '',
		D: '线悬世界 World on a Wire',
		E: 'Participating artists :  Mariia Fedorova LU Fei & LEI Jianhao JooYoung Oh Sascha Pohflepp (1978-2019), Matthew Lutz, and Alessia Nigretti Pete Jiadong Qiang Tabor Robak Rachel Rossin Timur Si-Qin Theo Triantafyllidis YE Nan ZZYW (Zhenzhen Qi & Yang Wan)',
		F: "institution's website",
		G: '现代汽车中心首尔 Hyandai Motorstudio New Museum',
		H: 'New Museum, winter, 2019, NYC',
		I: 'Hyandai Motorstudio & Rhizome',
		J: 'Michael Connor 陈嘉莹',
		K: 'https://rhizome.org/editorial/2021/jan/28/now-live-world-on-a-wire-online-and-off/',
		L: 'https://worldonawire.net/',
		M: '',
		N: '“World on a Wire” explores artistic practices engaged with emergent born-digital technologies such as augmented reality (AR), virtual reality (VR), and artificial intelligence (AI).',
		O: 'michael.connor@rhizome.org',
		P: 'generative website designed by Yehwan Song',
		Q: ['./images/22.png']
	},
	color: '#ff0000'
},
{
	type: '画廊线上展览 Gallery‘s Online Exhibition',
	year: '2021/6/21',
	name: 'Free Port',
	person: 'Epoch Gallery',
	info: {
		A: '画廊线上展览Commercial Gallery‘s Online Exhibition',
		B: '2021/6/21',
		C: '2021/10/08',
		D: 'Free Port',
		E: 'Neïl Beloufa | Sarah Rosalena Brady | Alice Bucknell | Juan Covelli | Alexandra Koumantaki | Amanda Ross-Ho | Hirad Sab',
		F: "Epoch Gallery 画廊官方网站",
		G: '',
		H: '',
		I: '',
		J: '',
		K: 'https://epoch.gallery/',
		L: 'https://epoch.gallery/Freeport/',
		M: '',
		N: '',
		O: '',
		P: '',
		Q: ['./images/23.png']
	},
	color: '#ff008a'
},
{
	type: "学生线上展览Student's Online Exhibition",
	year: '2021/6/20',
	name: '清华大学美术学院2021届线上毕业作品展',
	person: '鲁晓波（清美院长）',
	info: {
		A: "学生线上展览Student's Online Exhibition",
		B: '2021/6/20',
		C: '',
		D: '清华大学美术学院2021届线上毕业作品展',
		E: '2021届本科生 研究生',
		F: "学校官方网站",
		G: '清华大学美术学院（设计研发）',
		H: '阿里巴巴人际自然交互实验室、阿里云资源支持',
		I: '',
		J: '鲁晓波（清美院长）',
		K: '',
		L: 'https://exhibition.ad.tsinghua.edu.cn/2021/',
		M: '',
		N: '',
		O: 'gymyjwb@mailoa.tsinghua.edu.cn',
		P: '',
		Q: ['./images/24.png', './images/24-1.png']
	},
	color: '#f318bf'
},
{
	type: '研究机构线上展览Research Institute Online Exhibition',
	year: '2021/6/11',
	name: 'Printing R-Evolution 1450-1500',
	person: '',
	info: {
		A: '研究机构线上展览Research Institute Online Exhibition',
		B: '2021/6/11',
		C: '',
		D: 'Printing R-Evolution 1450-1500',
		E: '',
		F: "University official Website",
		G: 'University of Oxford',
		H: '',
		I: '',
		J: '',
		K: 'https://mp.weixin.qq.com/s/Y691-ri0rB3G2BUf366_lQ',
		L: 'https://www.printingrevolution.eu/virtual-exhibition-printing-revolution/',
		M: '',
		N: '',
		O: 'info@printingrevolution.eu',
		P: '',
		Q: ['./images/25.png']
	},
	color: '#b53cbe'
},
{
	type: "学生线上展览Student's Online Exhibition",
	year: '2021/6/10',
	name: '中央美术学院2021毕业展',
	person: '范迪安',
	info: {
		A: "学生线上展览Student's Online Exhibition",
		B: '2021/6/10',
		C: '',
		D: '中央美术学院2021毕业展',
		E: '2021届本科生 研究生',
		F: "学校官方网站",
		G: '中央美术学院',
		H: '360度全景制作：雅昌文化（集团）制作公司',
		I: '',
		J: '范迪安',
		K: 'https://mp.weixin.qq.com/s/b6y9vNKKTmnAKsrSxUihOg',
		L: 'http://2021art.cafa.edu.cn/pc/fullView',
		M: '',
		N: '',
		O: '',
		P: '',
		Q: ['./images/26.png', './images/26-1.png']
	},
	color: '#964ec6'
},
{
	type: '艺术家平台Artist Stutio/Network',
	year: '2021/6/1',
	name: '史莱姆引擎 海洋2.0',
	person: '',
	info: {
		A: '艺术家平台Artist Stutio/Network',
		B: '2021/6/1',
		C: '',
		D: '史莱姆引擎 海洋2.0',
		E: '李汉威、刘树臻、方阳、善良',
		F: "artist website",
		G: '',
		H: '',
		I: '北鸥设计',
		J: '',
		K: '史莱姆引擎：百人展《海洋》开幕中',
		L: 'https://www.slimeengine.com/oc2/',
		M: '',
		N: '史莱姆引擎（www.slimeengine.com）创立于2017年，现由李汉威、刘树臻、方阳、善良共同运营。史莱姆引擎是一个线上的平台性组织，利用不受时间和空间限制的虚拟世界，开发前所未有的作品创作、展览策划和观展形式。',
		O: '',
		P: '',
		Q: ['./images/27.png']
	},
	color: '#7e53c6'
},
{
	type: '画廊NFT发行Gallery‘s NFT Release',
	year: '2021/6/1',
	name: 'In The Darkest Hour I Am By Your Side',
	person: 'snark.art; Duke Riley',
	info: {
		A: '画廊NFT发行Gallery‘s NFT Release',
		B: '2021/6/1',
		C: '',
		D: 'In The Darkest Hour I Am By Your Side',
		E: 'Duke Riley',
		F: "e-gallery website; blockchain",
		G: 'snark.art',
		H: '',
		I: '',
		J: 'snark.art; Duke Riley',
		K: '',
		L: 'https://snark.art/non-essential-consultants/',
		M: '',
		N: 'Duke Riley’s three-channel video installation combines narrative and documentary filmmaking to portray an allegorical history implicating a duo of outlaw operatives responsible for a bed bug outbreak in Washington, DC.',
		O: '',
		P: 'Blockchain Participants',
		Q: ['./images/28.png']
	},
	color: '#6d66b5'
},
{
	type: '画廊线上展览Gallery‘s Online Exhibition',
	year: '2021/5/11',
	name: 'Tabula Rasa Tablet线上群展',
	person: 'Tabula Rasa 画廊',
	info: {
		A: '画廊线上展览Commercial Gallery‘s Online Exhibition',
		B: '2021/5/11',
		C: '未知',
		D: 'Tabula Rasa Tablet线上群展',
		E: '黄安澜、李文嘉、孙萌、王裕言、覃小诗、徐思行',
		F: "微信小程序 TR Tablet",
		G: 'Tabula Rasa 画廊',
		H: '',
		I: '',
		J: 'Tabula Rasa 画廊',
		K: 'https://mp.weixin.qq.com/s/s0vTT2p0AcyZBDVgo7TNUA',
		L: '微信小程序搜索 TR Tablet',
		M: '',
		N: '',
		O: '',
		P: '',
		Q: ['./images/29.png', './images/29-1.png']
	},
	color: '#546cbb'
},
{
	type: '画廊NFT发行Gallery‘s NFT Release',
	year: '2021/5/1',
	name: 'Sometimes A Thousand Twandling Instruments',
	person: 'snark.art; Volkmar Klien',
	info: {
		A: '画廊NFT发行Gallery‘s NFT Release',
		B: '2021/5/1',
		C: '',
		D: 'Sometimes A Thousand Twandling Instruments',
		E: 'Volkmar Klien',
		F: "e-gallery website; blockchain",
		G: 'snark.art',
		H: '',
		I: '',
		J: 'snark.art; Volkmar Klien',
		K: '',
		L: 'https://snark.art/1000-twangling-instruments',
		M: '',
		N: '',
		O: '',
		P: 'Blockchain Participants',
		Q: ['./images/30.png']
	},
	color: '#0075c2'
},
{
	type: '美术馆线上展Art Museum Online Exhibition',
	year: '2021/4/29',
	name: 'Spatial Affairs. Worlding',
	person: 'Curators: Giulia Bini, Lívia Nolasco-Rózsás',
	info: {
		A: '美术馆线上展 Art Museum Online Exhibition',
		B: '2021/4/29',
		C: '30.08.2023',
		D: 'Spatial Affairs. Worlding',
		E: 'Morehshin Allahyari, Besorolás Alatt (Unrated), Petra Cortright, Louise Drulhe, Sam Ghantous, JODI, Sam Lavigne & Tega Brain, Oliver Laric, Jan Robert Leegte, Rosa Menkman, Sascha Pohflepp & Alessia Nigretti & Matthew Lutz, Rafaël Rozendaal',
		F: "project's website",
		G: 'Ludwig Múzeum Budapest and ZKM | Karlsruhe',
		H: 'Design and programming: The Rodina (Tereza and Vit Ruller)',
		I: 'Soundscape: Enrico Boccioletti',
		J: 'Curators: Giulia Bini, Lívia Nolasco-Rózsás',
		K: 'ZKM',
		L: 'https://spatialaffairs.beyondmatter.eu/en',
		M: '',
		N: 'Conceived as part of the exhibition »Spatial Affairs«, presented at the Ludwig Museum – Museum of Contemporary Art, Budapest, »Spatial Affairs. Worlding – A tér világlása« is an exploratory online environment, a virtual multi-user exhibition populated by crawling artworks, where visitors’ avatars coexist with moving bodies of internet art and browser-based projects.',
		O: 'PAY ATTENTION TO HOW THE WEBSITE IS NAVIGATED. AND THE USE OF SOUNDSCAPE IN ONLINE EXHIBITIONS, E.G.: 史莱姆引擎、央美毕业展2021、PMVABF艺术家网站',
		P: '',
		Q: ['./images/31.png', './images/31-1.png']
	},
	color: '#008abf'
},
{
	type: '画廊线上展览Gallery‘s Online Exhibition',
	year: '2021/4/20',
	name: '春天棕榈（Spring Times, Palm Trees）线上群展',
	person: '李石影',
	info: {
		A: '画廊线上展览Gallery‘s Online Exhibition',
		B: '2021/4/20',
		C: '2021/5/30',
		D: '春天棕榈（Spring Times, Palm Trees）线上群展',
		E: 'Vikram Divecha、郝量、Amy Lien & Enzo Camacho（与Marc Asekhame合作）、笹本晃、Sung Tieu、袁中天',
		F: "荔枝FM/小宇宙/苹果podcast/汽水儿平台/美凯龙艺术中心微信公众号/美凯龙艺术中心官方网站",
		G: '天线空间',
		H: '',
		I: '',
		J: '李石影',
		K: 'http://antenna-space.com/zh/viewing_room/chuntianzonglu/#',
		L: 'http://antenna-space.com/viewing_room/chuntianzonglv/',
		M: '',
		N: '',
		O: '',
		P: '',
		Q: ['./images/32.png']
	},
	color: '#0092ff'
},
{
	type: '美术馆线上展 Art Museum Online Exhibition',
	year: '2021/4/11',
	name: 'Jazmina Figueroa. Call Signs',
	person: 'Theodoulos Polyviou',
	info: {
		A: '美术馆线上展 Art Museum Online Exhibition',
		B: '2021/4/11',
		C: '30.09.2023',
		D: 'Jazmina Figueroa. Call Signs',
		E: 'Jazmina Figueroa',
		F: "institution's website",
		G: 'ZKM | Center for Art and Media Karlsruhe',
		H: '',
		I: 'Digital Consultant: Andrew Madden IT: Christian Lölkes',
		J: 'Theodoulos Polyviou',
		K: 'https://zkm.de/en/exhibition/2021/11/jazmina-figueroa-call-signs',
		L: 'https://fantastic-confabulations.beyondmatter.eu/',
		M: '',
		N: '',
		O: '',
		P: '',
		Q: ['./images/33.png']
	},
	color: '#0092d3'
},
{
	type: '研究机构线上展览Institute‘s Online Exhibition',
	year: '2021/4/2',
	name: 'Data Visualization and the Modern Imagination',
	person: 'RJ Andrews，G. Salim Mohammed，Andrea Renner，Rueiyun Wang',
	info: {
		A: '研究机构线上展览Research Institute Online Exhibition',
		B: '2021/4/2',
		C: '',
		D: 'Data Visualization and the Modern Imagination',
		E: '',
		F: "University official Website",
		G: 'Stanford University',
		H: '',
		I: '',
		J: 'RJ Andrews，G. Salim Mohammed，Andrea Renner，Rueiyun Wang',
		K: 'https://mp.weixin.qq.com/s/0Ir7StKFzGbqo0AwVFStXw',
		L: 'https://exhibits.stanford.edu/dataviz',
		M: '',
		N: 'history of science; information graphics; maps',
		O: '',
		P: '',
		Q: ['./images/34.png', './images/34-1.png']
	},
	color: '#00908e'
},
{
	type: '画廊线上展览Gallery‘s Online Exhibition',
	year: '2021/4/1',
	name: '残酷仙境Wonderland',
	person: 'Peter Wu+',
	info: {
		A: '画廊线上展览Gallery‘s Online Exhibition',
		B: '2021/4/1',
		C: '',
		D: '残酷仙境Wonderland',
		E: '武子杨（Ziyang Wu）张怡（Patty Chang）多米尼克·冯（Dominique Fung）克里斯蒂娜·王（Christine Wang）欧阳凯丽（Catalina Ouyang）沈心怡（Sydney Shen）林从欣（Candice Lin）',
		F: "Epoch Gallery 画廊官方网站",
		G: '',
		H: '',
		I: '',
		J: 'Peter Wu+',
		K: 'http://www.heichimagazine.org/zh/articles/700/wonderland-surviving-horror-and-monstrosity',
		L: 'https://epoch.gallery/Wonderland/index.htm',
		M: 'NFT 项目；黑齿杂志展评《Wonderland: Surviving Horror and Monstrosity》Wonderland is an online group exhibition at EPOCH, an artist-run virtual experiment by Peter Wu+',
		N: '',
		O: 'info@epoch.gallery',
		P: '',
		Q: ['./images/35.png']
	},
	color: '#00905c'
},
{
	type: '美术馆线上展 Art Museum Online Exhibition',
	year: '2021/3/26',
	name: 'PSA2020 青策计划他山之石，新代理人',
	person: '蔡星洋、龙星如',
	info: {
		A: '美术馆线上展Art Museum Online Exhibition',
		B: '2021/3/26',
		C: '2021/06/27',
		D: 'PSA2020 青策计划他山之石，新代理人',
		E: '',
		F: "上海当代艺术博物馆、《平面游击》官方网站",
		G: '',
		H: '',
		I: '',
		J: '蔡星洋、龙星如',
		K: 'https://irislong.xyz/BlueCables',
		L: '',
		M: '',
		N: '驻地计划',
		O: '',
		P: '',
		Q: ['./images/36.png']
	},
	color: '#0068ff'
},
{
	type: '美术馆线上展Art Museum Online Exhibition',
	year: '2021/3/26',
	name: 'PSA2020 青策计划 “平面游击：起来！数字失神者”',
	person: '吴月、何竞飞',
	info: {
		A: '美术馆线上展 Art Museum Online Exhibition',
		B: '2021/3/26',
		C: '2021/06/27',
		D: 'PSA2020 青策计划 “平面游击：起来！数字失神者”',
		E: '参展艺术家：曹澍、陈天灼、葛宇路、何守一、黄安澜、夏诚安、羊喘儿、叶甫纳、赵邦、张小涛、张心一、左仆拉',
		F: "上海当代艺术博物馆、《平面游击》官方网站",
		G: '',
		H: '',
		I: '',
		J: '吴月、何竞飞',
		K: 'https://mp.weixin.qq.com/s/wLeaQdyoDebSlsj7k7g8Xg',
		L: 'https://ecp2020-flatland.powerstationofart.com/',
		M: '',
		N: '',
		O: '',
		P: '',
		Q: ['./images/37.png']
	},
	color: '#009037'
},
{
	type: '美术馆线上展Art Museum Online Exhibition',
	year: '2021/3/15',
	name: '“卡壳”（Cacotopia）线上长期项目',
	person: '黄格勉、陈於建',
	info: {
		A: '美术馆线上展 Art Museum Online Exhibition',
		B: '2021/3/15',
		C: '未知',
		D: '“卡壳”（Cacotopia）线上长期项目',
		E: '“外出午餐”小组，Saurabh Datta，Winne Wu，童义欣;未来主人',
		F: "荔枝FM/小宇宙/苹果podcast/汽水儿平台/美凯龙艺术中心微信公众号/美凯龙艺术中心官方网站",
		G: '美凯龙艺术中心',
		H: '',
		I: '',
		J: '黄格勉、陈於建',
		K: 'https://mp.weixin.qq.com/s/stUSK1YRs7i-lHYwa65Cpg',
		L: 'http://www.macallineart.org/zh/events/488/n-a',
		M: '',
		N: 'Sound Art声音艺术；收集不同声音的播客项目',
		O: '',
		P: 'soundscape',
		Q: ['./images/38.png']
	},
	color: '#017bb6'
},
{
	type: '艺术书展Virtual Book Fair',
	year: '2021/2/24',
	name: "PMVABF （Printed Matter's Virtual Art Book Fair)",
	person: 'Printed Matter Inc.',
	info: {
		A: '艺术书展Virtual Book Fair',
		B: '2021/2/24',
		C: '2021/02/28',
		D: "PMVABF （Printed Matter's Virtual Art Book Fair)",
		E: '400 Exhibitor List',
		F: "独立网站Individual Website",
		G: 'Printed Matter Inc.',
		H: '',
		I: 'supported by CargoSite',
		J: 'Printed Matter Inc.',
		K: 'https://mp.weixin.qq.com/s/39EdPZmP0c6e6zvAIlAm5Q',
		L: 'https://pmvabf.org/',
		M: '',
		N: '',
		O: '',
		P: '',
		Q: ['./images/39.png', './images/39-1.png', './images/39-2.png']
	},
	color: '#0177d9'
},
{
	type: '画廊线上展览Commercial Gallery‘s Online Exhibition/NFT release',
	year: '2021/1/9',
	name: 'SUBSTRATA',
	person: 'Epoch Gallery',
	info: {
		A: '画廊线上展览Commercial Gallery‘s Online Exhibition/NFT release',
		B: '2021/1/9',
		C: '2021/03/05',
		D: 'SUBSTRATA',
		E: 'Patricia Fernández | Nikita Gale | Won Ju Lim | Gina Osterloh | Paul Pescador | Kristin Posehn | Gabie Strong | Sterling Wells | Haena Yoo',
		F: "Epoch Gallery 画廊官方网站",
		G: 'Epoch Gallery',
		H: 'Epoch Gallery',
		I: 'Epoch Gallery',
		J: 'Epoch Gallery',
		K: 'https://epoch.gallery/',
		L: 'https://epoch.gallery/substrata/',
		M: '',
		N: '',
		O: '',
		P: '',
		Q: ['./images/40.png']
	},
	color: '#2667f7'
},
{
	type: '研究机构线上展览Institute‘s Online Exhibition',
	year: '2021/1/1',
	name: 'The Virtual Fashion Archive',
	person: 'Super Bureau',
	info: {
		A: '研究机构线上展览Institute‘s Online Exhibition',
		B: '2021/1/1',
		C: '',
		D: 'The Virtual Fashion Archive',
		E: 'Super Bureau',
		F: "artist website",
		G: 'Super Bureau',
		H: '',
		I: '',
		J: '',
		K: '',
		L: 'https://www.virtualfashionarchive.com/garments/?id=issey-miyake-dress-1996',
		M: 'https://superficial.studio/',
		N: 'The Virtual Fashion Archive is a collection of archival garments brought to life in new digital dimensions.',
		O: '',
		P: '',
		Q: ['./images/41.png']
	},
	color: '#3d5de5'
},
{
	type: '画廊NFT发行Gallery‘s NFT Release',
	year: '2021/1/1',
	name: '89 seconds Atomized',
	person: 'snark.art; Eve Sussman; Rufus Corporation',
	info: {
		A: '画廊NFT发行Gallery‘s NFT Release',
		B: '2021/1/1',
		C: '',
		D: '89 seconds Atomized',
		E: 'Eve Sussman | Rufus Corporation',
		F: "e-gallery website; blockchain",
		G: 'snark.art',
		H: '',
		I: '',
		J: 'snark.art; Eve Sussman; Rufus Corporation',
		K: '',
		L: 'https://snark.art/89seconds/',
		M: '',
		N: 'Each token (or "atom") contains a unique 9:44 minute 20x20 pixel video fragment of the original artwork ’89 seconds at Alcázar’ (in collections of MoMA, Whitney and Leeum museums). Join our incredible growing community of over 300 current atom holders!',
		O: '',
		P: '',
		Q: ['./images/42.png']
	},
	color: '#6457ff'
},
{
	type: '线上档案Digital Archive',
	year: '2021/1/1',
	name: 'Curating Online',
	person: 'Marialaura Ghidini (Collaborators: Vivek Chockalingam; Padmini Ray Murray; Vidya Shividas; Gaia Tedone; Joasia Krysa)',
	info: {
		A: '线上档案Digital Archive',
		B: '2021/1/1',
		C: '',
		D: 'Curating Online',
		E: 'Marialaura Ghidini',
		F: "独立网站Individual Website",
		G: 'In Partnership With The Exhibition Research Lab (Erl) At The Liverpool John Moores University',
		H: 'Network (Events) Nation25 – Rome, Italy Walkin Studios – Bangalore, India Mo.Ca. – Brescia, Italy D.A.M.S. – Università Cattolica Del Sacro Cuore – Brescia, Italy',
		I: 'WEBSITE AND PROGRAMMING BY ROCÍO FATÁS',
		J: 'Marialaura Ghidini (Collaborators: Vivek Chockalingam; Padmini Ray Murray; Vidya Shividas; Gaia Tedone; Joasia Krysa)',
		K: 'https://p-dpa.net/',
		L: 'https://www.curating.online',
		M: '',
		N: 'It  collects some fun online exhibitions in Europe',
		O: '',
		P: '',
		Q: ['./images/43.png']
	},
	color: '#8c40ff'
},
{
	type: '研究机构线上展览Institute‘s Online Exhibition',
	year: '2020/12/30',
	name: '中国当代艺术年鉴展2019',
	person: '朱青生',
	info: {
		A: '研究机构线上展览Institute‘s Online Exhibition',
		B: '2020/12/30',
		C: '',
		D: '中国当代艺术年鉴展2019',
		E: '李燎 LI Liao, 周姜杉 ZHOU Jiangshan, 文皆俊杰 WEN Jie Junjie, 于洋 YU Yang, 欧阳春 OUYANG Chun, 劳家辉 LAO Jiahui, 梁铨 LIANG Quan, 陈维 CHEN Wei, 李涛 LI Tao, 杨圆圆 YANG Yuanyuan, 佩恩恩 PEI Enen, aaajiao (徐文恺 XU Wenkai), 任伦 REN Lun, 黄于纲 HUANG Yugang, 杨诘苍 YANG Jiecang, 程新皓 CHENG Xinhao, 能尖日 Nhozagri, 尤阿达 YOU Ada, 山河跳！Mountain River Jump!, 耿雪 GENG Xue, 姚海 YAO Hai, 李琳琳 LI Linlin, 隋建国 SUI Jianguo',
		F: "坪山美术馆",
		G: '中国现代艺术档案CMAA',
		H: '吴作人国际美术基金会',
		I: '坪山美术馆',
		J: '朱青生',
		K: 'https://www.artexb.com/portfolio/exb105/',
		L: 'https://www.artexb.com/pano/exb105/?startscene=0&startactions=lookat(187.69,8.94,120,0,1);',
		M: '',
		N: '坪山美术馆全景互动平台',
		O: '',
		P: '',
		Q: ['./images/44.png']
	},
	color: '#b400ff'
},
{
	type: '美术馆线上展Art Museum Online Exhibition',
	year: '2020/12/24',
	name: '“赤屏”（Bare Screen）线上长期项目',
	person: '富源',
	info: {
		A: '美术馆线上展 Art Museum Online Exhibition',
		B: '2020/12/24',
		C: '未知',
		D: '“赤屏”（Bare Screen）线上长期项目',
		E: '陶辉、陈天灼、刘沁敏、刘窗、佩恩恩、谭婧与郑可、张文心、唐潮、胡伟、刘娃',
		F: "美凯龙艺术中心官方网站",
		G: '',
		H: '',
		I: '',
		J: '富源',
		K: 'http://www.macallineart.org/zh/events/390/n-a',
		L: 'http://www.macallineart.org/zh/events/390/n-a',
		M: '',
		N: '声音艺术；收集不同声音的播客项目',
		O: '',
		P: '',
		Q: ['./images/45.jpg']
	},
	color: '#b62dc8'
},
{
	type: "美术馆线上展 Art Museum Online Exhibition",
	year: "2020/11/21",
	name: "We=Link：辺 线上平行展厅",
	person: "张尕",
	info: {
		A: '美术馆线上展 Art Museum Online Exhibition',
		B: '2020/11/21',
		C: '未知',
		D: 'We=Link：辺 线上平行展厅',
		E: '陈朋朋，郭城，知识机器研究（Knowbotic Research），LAN，梁雨荭，刘行，劳伦·李·麦卡锡（Lauren Lee McCarthy），凯尔·麦克唐纳（Kyle McDonald）沃夫冈·施泰勒（Wolfgang Staehle），明天（Ubermorgen），徐昊旻，赵华，周蓬岸等',
		F: "新时线媒体艺术中心官方网站",
		G: '',
		H: 'artport/ The Whitney Museum of American Art',
		I: '',
		J: '张尕',
		K: 'https://mp.weixin.qq.com/s/u_SuvrKrAO9l-RVSnoSe_g',
		L: 'http://we-link.chronusartcenter.org/sideways/',
		M: '',
		N: '中央美术学院美术馆（北京），卡尔斯鲁厄艺术与媒体中心｜ZKM（卡尔斯鲁厄），HeK（巴塞尔电子艺术中心），V2_不稳定媒体（鹿特丹），欧洲核子研究中心艺术项目（日内瓦），Elektra国际电子艺术节（蒙特利尔），列奥纳多/国际艺术-科学与技术协会，白南准美术馆（首尔），哥本哈根当代艺术馆（哥本哈根），光艺术空间（柏林）；合作：惠特尼美国艺术博物馆“艺术港（Artport）”项目 (纽约)',
		O: 'media@chronusartcenter.org',
		P: '',
		Q: ['./images/46.png']
	},
	color: '#d300c4'
},
{
	type: "研究机构线上展览Research Institute Online Exhibition",
	year: "2020/11/1",
	name: "Ciphers, Codes and Notes: Crafting Knowledge in the Medieval and Modern Worlds",
	person: "",
	info: {
		A: '研究机构线上展览Research Institute Online Exhibition',
		B: '2020/11/1',
		C: 'January 2021',
		D: 'Ciphers, Codes and Notes: Crafting Knowledge in the Medieval and Modern Worlds',
		E: '',
		F: "Microsoft Sway",
		G: 'McClay Library',
		H: '',
		I: '',
		J: '密码学，博物传统与神迹治疗：近期三个科学史主题的线上展览',
		K: 'https://mp.weixin.qq.com/s?__biz=MzAwODMxMTk3NQ==&mid=2247484124&idx=1&sn=2e3b27cc931ec68ba81cc0cce83f2898&chksm=9b718714ac060e02bf0973f99ecd631945ec631fb0670be878d329564a33eef24cb085a0d81e&scene=21',
		L: 'https://sway.office.com/WDT3WAaPQ0JjDdCf ',
		M: '',
		N: 'history of science; information graphics',
		O: '',
		P: '',
		Q: ['./images/47.png', './images/47-1.png', './images/47-2.png']
	},
	color: '#ed00b7'
},
{
	type: "艺术书展Virtual Book Fair",
	year: "2020/11/1",
	name: "2020 Tokyo Virtual Art Book Fair",
	person: "Tokyo Virtual Art Book Fair",
	info: {
		A: '艺术书展Virtual Book Fair',
		B: '2020/11/1',
		C: '',
		D: '2020 Tokyo Virtual Art Book Fair',
		E: "A a quiet day(Japan) akama saeko(Japan) Akane komatsu(Japan) AKIKO KANO / CANOO(Japan) AL / KiKi inc.(Japan) ALBATRO DESIGN(Japan) Alicia's Klassic Kool Shoppe(Canada) ALIENS BOOKS(Japan) Allright(Japan)	Almine Rech Editions(Belgium)	Altered Zones(USA)	Animal Press(Belgium)	Aperture Brought Me Here(Thailand)	applause(Japan) ARACHNE & OSC BROTHERS(Japan) ART BOOK CO-OP online(Japan) Art Byte Critique(Japan) Asami Togawa / Togawa-shoten(Japan) assignments(Japan) AWH?(Japan) Aēsop(Japan)",
		F: "Online+Offline Venue",
		G: '',
		H: 'The Tokyo Art Book Fair/ Special Assistance from the Museum of Contemporary Art Tokyo operated by Tokyo Metropolitan Foundation for History and Culture',
		I: '',
		J: "Tokyo Virtual Art Book Fair",
		K: '',
		L: 'https://2020.virtualartbookfair.com/',
		M: '',
		N: '',
		O: '',
		P: '',
		Q: ['./images/48.png', './images/48-1.png', './images/48-2.png']
	},
	color: '#ea0094'
},
{
	type: "学生线上展览Student's Online Exhibition",
	year: "2020/10/28",
	name: "“我们人类在火星” 线上群展",
	person: '总策划：薛天宠、王乃一；策展团队	贺彦朝、秦漫、任庆齐、张千艺、黄筱茜、翟苑延',
	info: {
		A: "学生线上展览Student's Online Exhibition",
		B: '2020/10/28',
		C: '未知',
		D: "“我们人类在火星” 线上群展",
		E: '参展艺术家：艾逸天、李若菡、李思慧、梁文华、苏永健、温晓彤、吴碧琳、熊樱菲',
		F: "我们人类在火星 官方网站",
		G: '中央美术学院设计学院，联合中央圣马丁艺术与设计学院',
		H: '网龙网络公司提供技术支持',
		I: '',
		J: '总策划：薛天宠、王乃一；策展团队	贺彦朝、秦漫、任庆齐、张千艺、黄筱茜、翟苑延',
		K: 'https://mp.weixin.qq.com/s/V49Uy5K_76l1t0JpKOKKWg',
		L: 'https://design.cafa.edu.cn/onlineexhibition/mars/',
		M: '',
		N: '总策划：薛天宠、王乃一；学术主持：宋协伟；学术顾问：张欣荣、Prem Krishnamurthy、纪玉洁、李贝壳、龙星如、Alison Green、Lee Weinberg；技术顾问：葛岩、林通、何秀凤',
		O: 'wehumanonmars@gmail.com',
		P: '',
		Q: ['./images/49.png', './images/49-1.png']
	},
	color: '#c82883'
},
{
	type: "画廊线上展览Commercial Gallery‘s Online Exhibition/NFT release",
	year: "2020/9/5",
	name: "Labyrinth",
	person: "Peter Wu+",
	info: {
		A: '画廊线上展览Commercial Gallery‘s Online Exhibition/NFT release',
		B: '2020/9/5',
		C: '2020/10/23',
		D: 'Labyrinth',
		E: 'Dorit Cypis | Danielle Dean | Jibade-Khalil Huffman | Lito Kattou | Amir Nikravan | Christian Ramirez | Paul Rosero Contreras',
		F: "e-gallery website; blockchain",
		G: 'Epoch Gallery',
		H: '',
		I: 'The pavilion for LABYRINTH was built by Amir Nikravan.',
		J: '',
		K: '',
		L: 'https://epoch.gallery/labyrinth/',
		M: '',
		N: '',
		O: '',
		P: '',
		Q: ['./images/50.png']
	},
	color: '#b94373'
},
{
	type: "研究机构线上展览Research Institute Online Exhibition",
	year: "2020/7/25",
	name: "Scientific Icons: Autobiographies and Portraits of Early Modern Bolognese Naturalists ",
	person: "",
	info: {
		A: '研究机构线上展览Research Institute Online Exhibition',
		B: '2020/7/25',
		C: '2020/9/30',
		D: 'Scientific Icons: Autobiographies and Portraits of Early Modern Bolognese Naturalists ',
		E: 'Ulisse Aldrovandi,Girolamo Cardano',
		F: "Museum official Website",
		G: 'MUSEO DI PALAZZO POGGI, BOLOGNA',
		H: '',
		I: '',
		J: '密码学，博物传统与神迹治疗：近期三个科学史主题的线上展览',
		K: 'https://mp.weixin.qq.com/s?__biz=MzAwODMxMTk3NQ==&mid=2247484124&idx=1&sn=2e3b27cc931ec68ba81cc0cce83f2898&chksm=9b718714ac060e02bf0973f99ecd631945ec631fb0670be878d329564a33eef24cb085a0d81e&scene=21',
		L: 'https://www.iconediscienza.it/en/',
		M: '',
		N: 'history of science; information graphics, local history, bologna, 展册可下载',
		O: '',
		P: '',
		Q: ''
	},
	color: '#b84941'
},
{
	type: "画廊线上展览Commercial Gallery‘s Online Exhibition",
	year: "2020/7/24",
	name: "CritCritical Zones: Observatories for Earthly Politics at KM Center for Art and Media Karlsruhe",
	person: "Bruno Latour and Peter Weibel with Martin Guinard and Bettina Korintenberg",
	info: {
		A: '画廊线上展览Commercial Gallery‘s Online Exhibition',
		B: '2020/7/24',
		C: '09/01/2022',
		D: 'CritCritical Zones: Observatories for Earthly Politics at KM Center for Art and Media Karlsruhe',
		E: 'Barbara Zoé Kiolbassa (museum communication), Jessica Menger (curatorial assistance), Daniel Irrgang (web editor and coordinator Critical Zones Study Group)',
		F: "institution's website",
		G: 'ZKM | Center for Art and Media Karlsruhe',
		H: '',
		I: '',
		J: 'Bruno Latour and Peter Weibel with Martin Guinard and Bettina Korintenberg',
		K: '',
		L: 'https://critical-zones.zkm.de/#!/',
		M: '',
		N: '“Who are we? What are we? Who and what are ‘we’ that is not only human?” (Donna Haraway) Welcome to the Critical Zone.',
		O: '',
		P: '',
		Q: ['./images/52.png']
	},
	color: '#bd4700'
},
{
	type: "艺术家作品发布Artist Digital Project",
	year: "2020/7/11",
	name: "陆扬：妄想世界 + 陸揚地獄（现场表演直播）",
	person: "",
	info: {
		A: '艺术家作品发布Artist Digital Project',
		B: '2020/7/11',
		C: '',
		D: '陆扬：妄想世界 + 陸揚地獄（现场表演直播）',
		E: '艺术家：陆扬 | 策展人/ 首席制片：马修·斯毕巴 | 动作捕捉操作：元物（ Meta Objects） | 实时动作捕捉表演编程：元物（ Meta Objects） | 化身设计：陆扬 | 地狱背景创作：Extreme John | 妄想世界背景创作：陆扬 | 舞者：秦然 | 制片：罗斯·迈尔斯（Ross Miles） | 原声创作：Gameface | DJ Mix：Extreme John |直播解决方案：Tech Sound',
		F: "institution's website",
		G: '新时线媒体艺术中心',
		H: '',
		I: '',
		J: '',
		K: 'https://mp.weixin.qq.com/s/WvZCWbrGHqb0GeBkMTXKkQ',
		L: 'https://www.acmi.net.au/whats-on/gallery-5/lu-yang-delusional-world/',
		M: '',
		N: '',
		O: 'https://www.instagram.com/luyangasia/',
		P: '',
		Q: ['./images/53.jpeg']
	},
	color: '#ca3500'
},
{
	type: "画廊线上展览Commercial Gallery‘s Online Exhibition/NFT release",
	year: "2020/7/8",
	name: "Fallen Monuments",
	person: "Peter Wu+",
	info: {
		A: '画廊线上展览Commercial Gallery‘s Online Exhibition/NFT release',
		B: '2020/7/8',
		C: '2020/9/4',
		D: 'Fallen Monuments',
		E: 'Iván Argote | York Chang | Allana Clarke | Gala Porras-Kim | Ricardo Rivera | Marton Robinson | Conrad Ruiz',
		F: "e-gallery website; blockchain",
		G: 'Epoch Gallery',
		H: '',
		I: '',
		J: 'Peter Wu+',
		K: '',
		L: 'https://epoch.gallery/fallen-monuments/',
		M: '',
		N: '',
		O: '',
		P: '',
		Q: ['./images/54.png']
	},
	color: '#d42200'
},
{
	type: "学生线上展览Student's Online Exhibition",
	year: "2020/6/24",
	name: "Degree Show 2020Liverpool John Moores University",
	person: "",
	info: {
		A: "学生线上展览Student's Online Exhibition",
		B: '2020/6/24',
		C: '',
		D: 'Degree Show 2020Liverpool John Moores University',
		E: 'BA Fine Art',
		F: "School's Website",
		G: 'University of Liverpool',
		H: '',
		I: '',
		J: '',
		K: '',
		L: 'https://www.ljmu.ac.uk/about-us/faculties/faculty-of-arts-professional-and-social-studies/liverpool-school-of-art-and-design',
		M: '',
		N: '',
		O: '',
		P: '',
		Q: ['./images/55.png', './images/55-1.png']
	},
	color: '#e10000'
},
{
	type: "艺术家作品发布Artist Digital Project",
	year: "2020/6/13",
	name: "数字人：独生独死",
	person: "",
	info: {
		A: "艺术家作品发布Artist Digital Project",
		B: '2020/6/13',
		C: '',
		D: '数字人：独生独死',
		E: '陆扬',
		F: "线下美术馆+instagram发布（阶段性）",
		G: '上海外滩美术馆（等）',
		H: '舞蹈数据：kEnkEn 技术支持：FACEGOOD 纹身设计：大岛拓（OshimaTaku） 特别鸣谢：宝马艺术之旅',
		I: '',
		J: '',
		K: 'https://mp.weixin.qq.com/s/v79KwA-BACDHBiNa8FLC3w',
		L: '',
		M: '',
		N: '',
		O: 'https://www.instagram.com/luyangasia/',
		P: '',
		Q: ['./images/56.jpeg']
	},
	color: '#da0427'
},
{
	type: "学生线上展览Student's Online Exhibition",
	year: "2020/6/1",
	name: "",
	person: "",
	info: {
		A: "学生线上展览Student's Online Exhibition",
		B: '2020/6/1',
		C: '',
		D: 'RCA2020 Online Show毕业展',
		E: '2020届硕士研究生',
		F: "School's Website",
		G: 'Royal College of Art',
		H: '',
		I: '',
		J: '',
		K: 'https://2020.rca.ac.uk/',
		L: '',
		M: '',
		N: '',
		O: '',
		P: '',
		Q: ['./images/57.png']
	},
	color: '#cb312f'
},
{
	type: "画廊线上展览Commercial Gallery‘s Online Exhibition/NFT release",
	year: "2020/5/30",
	name: "Afterlife",
	person: "Peter Wu+",
	info: {
		A: "画廊线上展览Commercial Gallery‘s Online Exhibition/NFT release",
		B: '2020/5/30',
		C: '2020/7/19',
		D: 'Afterlife',
		E: 'Nancy Baker Cahill | Beatriz Cortez | Jesper Just | Ula Lucińska & Michał Knychaus | Stachu Szumski | Mark Verabioff | Alice Wang',
		F: "e-gallery website; blockchain",
		G: 'Epoch Gallery',
		H: '',
		I: '',
		J: 'Peter Wu+',
		K: '',
		L: 'https://epoch.gallery/afterlife',
		M: '',
		N: 'PAY ATTENTION to the space design in online exhibitions. 線上展覽中的空間構造。',
		O: '',
		P: '',
		Q: ['./images/58.png']
	},
	color: '#bb4824'
},
{
	type: "学生线上展览Student's Online Exhibition",
	year: "2020/5/20",
	name: "“彼时·此时——2020中央美院线上毕业季”线上群展",
	person: "央美策划团队",
	info: {
		A: "学生线上展览Student's Online Exhibition",
		B: '2020/5/20',
		C: '未知',
		D: '“彼时·此时——2020中央美院线上毕业季”线上群展',
		E: '范迪安等13个教学单位的31名博士研究生、375名硕士研究生、846名本科生',
		F: "线上展厅官方网站",
		G: '中央美术学院',
		H: '技术团队：网龙公司',
		I: '',
		J: '央美策划团队',
		K: 'https://mp.weixin.qq.com/s/AyL4uLmjVMG2OD0jglHv3g',
		L: 'https://art2020.cafa.edu.cn',
		M: 'https://art2020.cafa.edu.cn',
		N: 'krpano，Three.js两套图像引擎的技术积累进行融合，同时使用unity3D引擎最新版本HDRP高精度渲染技术，高度拟真还原美术馆展示效果',
		O: '',
		P: '',
		Q: ''
	},
	color: '#a55921'
},
{
	type: "画廊线上展览Commercial Gallery‘s Online Exhibition/NFT release",
	year: "2020/4/25",
	name: "End Demo",
	person: "Peter Wu+",
	info: {
		A: "画廊线上展览Commercial Gallery‘s Online Exhibition/NFT release",
		B: '2020/4/25',
		C: '2021/5/29',
		D: 'End Demo',
		E: 'Jessica Goehring | Kara Joslyn | Erica Mahinay | Jake Kean Mayman | Emanuel Röhss | Peter Wu+',
		F: "e-gallery website; blockchain",
		G: 'Epoch Gallery',
		H: '',
		I: '',
		J: 'Peter Wu+',
		K: '',
		L: 'https://epoch.gallery/end-demo/',
		M: '',
		N: '每个展览搭建一个虚构建筑作为展览空间,experimental exhibition space; virtual landscapes;  gamification',
		O: '',
		P: 'similar to We Human On Mars',
		Q: ['./images/60.png']
	},
	color: '#966323'
},
{
	type: "艺术家/组合线上项目Artist/Group Online Project",
	year: "2020/4/1",
	name: "Haha Service",
	person: "John Provencher ",
	info: {
		A: "艺术家/组合线上项目Artist/Group Online Project",
		B: '2020/4/1',
		C: '',
		D: 'Haha Service',
		E: 'John Provencher',
		F: "artist website",
		G: '',
		H: '',
		I: '',
		J: '',
		K: 'https://fruitful.school/',
		L: 'https://haha.services/',
		M: '',
		N: 'Online Publishing',
		O: '',
		P: '',
		Q: ''
	},
	color: '#7b6e22'
},
{
	type: "画廊线上展览Gallery‘s Online Exhibition",
	year: "2020/3/30",
	name: "“十个小品”（Ten Easy Pieces）线上特展",
	person: "张尕",
	info: {
		A: "画廊线上展览Gallery‘s Online Exhibition",
		B: '2020/3/30',
		C: '未知',
		D: '“十个小品”（Ten Easy Pieces）线上特展',
		E: '拉斐尔·巴斯迪德（Raphaël Bastide)、泰佳·布莱恩&山姆·拉文（Tega Brain & Sam Lavigne）、JODI、李维伊、埃文·罗斯（Evan Roth）、史莱姆引擎、赫尔穆特·史密斯（Helmut Smits）、徐文恺（aka aaajiao）、Yangachi、叶甫纳',
		F: "",
		G: '',
		H: '新时线媒体艺术中心、那比艺术中心（首尔）、新美术馆Rhizome（纽约）',
		I: 'MANA新媒体艺术平台；北鸥网站设计工作室',
		J: '张尕',
		K: 'https://www.leonardo.info/welink-ten-easy-pieces',
		L: 'http://we-link.chronusartcenter.org/teneasypieces/',
		M: '',
		N: '网站设计：北鸥',
		O: '',
		P: '',
		Q: ['./images/62.png']
	},
	color: '#6c7100'
},
{
	type: "研究机构线上展览Research Institute Online Exhibition",
	year: "2020/1/1",
	name: "Miracolous Healings Disease and divine intervention. Art reinterprets miracles in works from 14th to 20th centuries",
	person: "",
	info: {
		A: "研究机构线上展览Research Institute Online Exhibition",
		B:  "2020/1/1",
		C:  "",
		D:  "Miracolous Healings Disease and divine intervention. Art reinterprets miracles in works from 14th to 20th centuries",
		E:  "",
		F:  "Museum official Website",
		G:  "Uffizi, 2020",
		H:  "",
		I:  "",
		J:  "",
		K:  "密码学，博物传统与神迹治疗：近期三个科学史主题的线上展览",
		L:  "https://www.uffizi.it/en/online-exhibitions/miracolous-healings",
		M:  "",
		N:  "history of science; information graphics; 神迹治疗",
		O:  "",
		P:  "",
		Q: ['./images/63.png']
	},
	color: '#5a7600'
},
{
	type: "艺术家/组合线上项目Artist/Group Online Project",
	year: "2020/1/1",
	name: "Fruit School生成艺术项目（非展览）",
	person: "John Provencher",
	info: {
		A: "艺术家/组合线上项目Artist/Group Online Project",
		B:  "2020/1/1",
		C:  "",
		D:  "Fruit School生成艺术项目（非展览）",
		E:  "John Provencher  Laurel Schwulst ",
		F:  "artist website",
		G:  "",
		H:  "",
		I:  "WEB AS MAZE; FRUITFUL WEB",
		J:  "John Provencher",
		K:  "https://fruitful.school/",
		L:  "https://johnprovencher.com/shapes/",
		M:  "https://fruitful.school/blog/index.html",
		N:  "fruitful.school is an independently-run learning initiative for making “fruitful websites” founded in 2020 by laurel schwulst and john provencher.",
		O:  "fruitful.school is dedicated to exploring new ways of publishing together using the www.",
		P:  "winter 2021 workshop, participants will hang out and work together online to self-publish a piece to the www over the course of 6 weeks.",
		Q:  ['./images/64.png']
	},
	color: '#437900'
},
{
	type: "线上档案Digital Archive",
	year: "2020/1/1",
	name: "Cyberfeminism Index",
	person: "Mindy Seu",
	info: {
		A: "线上档案Digital Archive",
		B:  "2020/1/1",
		C:  "",
		D:  "Cyberfeminism Index",
		E:  "Melissa Aguilar, Chinmayi Arun, Cyborgrrrls, Salome Asega, Matthew Battles, Inés Benitez, Berkman Klein Center for the Internet & Society, Kelsey Brod, Agnes Cameron, Ruth Catlow, Soyoung Chong, Michael Connor, Sasha Costanza-Chock,Jessica Dheere, Brenda Dvoskin, Dragan Espenschield, Laura Forlano, Sarah Fox, Loraine Furter, Mariel García-Montes, Sal Hamerman, Geoff Han, Sam Hart , Melanie Hoff, Dragana Kaurin, Hanna Kim, Levin Kim, Malin Kuht,ei Liu, Mary Maggic, Judy Malloy, Shannon Mattern, Amye McCarther, Jasmine McNealy, Christine Meinders, Angeline Marie Michael Meitzler, MetaLab Harvard, Eric Moed, Sarah Newman,Chiara Fauda Pichet, Constanza Piña, David Reinfurt, Kalli Retzepi, Refresh Tech, Rhizome, Paola Ricaurte, Lozana Rossenova, Dorothy Santos, Andrew Scheinman, Jeffrey Schnapp, aurel Schwulst, Boaz Sender, Malkit Shoshan, Caroline Sinders, Hee-jeong Sohn, Cornelia Sollfrank, Abby Spinak, Salome Viljoen, Charlotte Webb, Faith Wilding, Xin Xin",
		F:  "project website;paperbook",
		G:  "New Museum",
		H:  "",
		I:  "The website was designed in collaboration with and developed by Angeline Meitzler, with frontend support from Janine Rosen and PDF support from Charles Broskoski. ",
		J:  "Mindy Seu",
		K:  "https://www.newmuseum.org/exhibitions/view/first-look-cyberfeminism-index",
		L:  "https://cyberfeminismindex.com/",
		M:  "Cyberfeminism Index is an in-progress online collection of resources for techno-critical works from 1990–2020, gathered and facilitated by Mindy Seu.",
		N:  "mindyseu@gmail.com",
		O:  "",
		P:  "",
		Q:  ['./images/65.png']
	},
	color: '#207d00'
},
{
	type: "Online  Exhibition",
	year: "2020/1/1",
	name: "The Museum of the World",
	person: "The British Museum",
	info: {
		A: "Online  Exhibition",
		B:  "2020/1/1",
		C:  "",
		D:  "The Museum of the World",
		E:  "The British Museum",
		F:  "eperimentwithgoogle",
		G:  "",
		H:  "",
		I:  "",
		J:  "The British Museum",
		K:  "",
		L:  "https://britishmuseum.withgoogle.com/",
		M:  "",
		N:  "",
		O:  "",
		P:  "Online  Exhibition",
		Q:  ['./images/66.png']
	},
	color: '#008525'
},
{
	type: "Museum comissioned artist's solo project",
	year: "2020/1/1",
	name: "NEW YORK APARTMENT",
	person: "Sam Lavigne; Tega Brain",
	info: {
		A: "Museum comissioned artist's solo project",
		B:  "2020/1/1",
		C:  "",
		D:  "NEW YORK APARTMENT",
		E:  "Sam Lavigne；Tega Brain",
		F:  "Museum official Website",
		G:  "the Whitney Museum of American Art",
		H:  "the Whitney Museum of American Art",
		I:  "",
		J:  "Sam Lavigne; Tega Brain",
		K:  "https://whitney.org/exhibitions/new-york-apartment",
		L:  "https://whitney.org/artport-commissions/new-york-apartment/index.html",
		M:  "https://getwellsoon.labr.io",
		N:  "這個項目與2020年5月的《Get Well Soon》都用到了data grabbing and visualization. 但是這個更加複雜。",
		O:  "JS語言",
		P:  "PAY ATTENTION : ARCHIVE!!! GATHERING!! COLLECTION!!!",
		Q: "",
	},
	color: '#008c2c'
},
{
	type: "览Research Institute Online Exhibition",
	year: "2019/1/1",
	name: "Gutenberg & After Europe's First Printers, 1450-1470",
	person: "",
	info: {
		A: "览Research Institute Online Exhibition",
		B:  "2019/1/1",
		C:  "",
		D:  "Gutenberg & After Europe's First Printers, 1450-1470",
		E:  "",
		F:  "University official Website",
		G:  "Princeton University",
		H:  "",
		I:  "",
		J:  "",
		K:  "",
		L:  "https://dpul.princeton.edu/gutenberg/",
		M:  "",
		N:  "history of science; information graphics",
		O:  "",
		P:  "",
		Q:  ['./images/68.png']
	},
	color: '#008c75'
},
{
	type: "艺术家/组合线上项目Artist/Group Online Project",
	year: "2019/1/1",
	name: "Weather Gradient 生成艺术项目（非展览）",
	person: "John Provencher",
	info: {
		A: "艺术家/组合线上项目Artist/Group Online Project",
		B:  "2019/1/1",
		C:  "",
		D:  "Weather Gradient 生成艺术项目（非展览）",
		E:  "John Provencher",
		F:  "artist website",
		G:  "",
		H:  "",
		I:  "",
		J:  "John Provencher",
		K:  "https://johnprovencher.com/",
		L:  "https://weathergradient.com/",
		M:  "IN BROOKLYN（初始设置艺术家工作室位置）（5 digit zip code）—",
		N:  "THE TEMPERATURE IS 32º F, CLEAR, WITH WINDS AT 8.75 MPH & HUMIDITY AROUND 53%. THE COLOR AND SPEED OF THE GRADIENT WAS GENERATED WITH THESE VALUES ON 2022/02/24 2:55:14 PM 渐变颜色根据实时气温、风速、潮湿程度自动生成。",
		O:  "johnprovencher@gmail.com",
		P:  "",
		Q:  ['./images/69.png']
	},
	color: '#00858a'
},
{
	type: "艺术家/组合线上项目Artist/Group Online Project",
	year: "2019/1/1",
	name: "Project Moonshot",
	person: "",
	info: {
		A: "艺术家/组合线上项目Artist/Group Online Project",
		B:  "2019/1/1",
		C:  "",
		D:  "Project Moonshot",
		E:  "John Provencher",
		F:  "project website",
		G:  "Nike Project Moonshot, New York",
		H:  "",
		I:  "",
		J:  "",
		K:  "",
		L:  "https://johnprovencher.com/moonshot/",
		M:  "https://left.gallery/work/uneel-cbggre-naq-gur-fbepreref-fgbar",
		N:  "",
		O:  "",
		P:  "",
		Q:  ['./images/70.png']
	},
	color: '#00808b'
},
{
	type: "艺术家/组合线上项目Artist/Group Online Project",
	year: "2019/1/1",
	name: "The Next Biennial Should Be Curated by a Machine – Experiment 1",
	person: "Joasia Krysa  Leonardo Impett  UBERMORGEN",
	info: {
		A: "艺术家/组合线上项目Artist/Group Online Project",
		B:  "2019/1/1",
		C:  "",
		D:  "The Next Biennial Should Be Curated by a Machine – Experiment 1",
		E:  "",
		F:  "美术馆官方网站 Museum's official Website",
		G:  "the Whitney Museum of American Art",
		H:  "",
		I:  "",
		J:  "Joasia Krysa  Leonardo Impett  UBERMORGEN",
		K:  "https://www.curating.online",
		L:  "https://whitney.org/artport-commissions/the-next-biennial/index.html",
		M:  "",
		N:  "The Next Biennial Should Be Curated by a Machine reimagines the future of curating in the light of Artificial Intelligence as a self-learning human-machine system. Developed as a collaboration between artists UBERMORGEN, digital humanist Leonardo Impett, and curator Joasia Krysa, this project features a group of technical machine learning processes collectively named B3(NSCAM).",
		O:  "The sound in the exhibition!",
		P:  "️PAY ATTENTION The soundscape in the exhibition! ️",
		Q:  ['./images/71.png']
	},
	color: '#0b7c9d'
},
{
	type: "美术馆线上展 Art Museum Online Exhibition",
	year: "2018/7/9",
	name: "Minecraft Infinity Project",
	person: "Joasia Krysa",
	info: {
		A: "美术馆线上展 Art Museum Online Exhibition",
		B:  "2018/7/9",
		C:  "2018/10/16",
		D:  "Minecraft Infinity Project",
		E:  "Joasia Krysa",
		F:  "Platform (game)Minecraft",
		G:  "Liverpool Biennial",
		H:  "in partnership with FACT",
		I:  "developed by Tony Guillan and Adam Clarke, in collaboration with map maker Dragnoz",
		J:  "Joasia Krysa",
		K:  "https://www.biennial.com/blog/28/09/2016/creating-the-worlds-largest-virtual-sculpture-in-minecraft",
		L:  "https://www.biennial.com/minecraft-infinity-project",
		M:  "",
		N:  "The Minecraft Infinity Project is a virtual world where players have come together online, during the course of this year’s Liverpool Biennial, to create a vast sculptural landscape and portrait of the festival.",
		O:  "",
		P:  "",
		Q:  ['./images/72.png']
	},
	color: '#0078b0'
},
{
	type: "学生线上展览Student's Online Exhibition",
	year: "2018/7/1",
	name: "Floating Swarm",
	person: "Raphaël Bastide",
	info: {
		A: "学生线上展览Student's Online Exhibition",
		B:  "2018/7/1",
		C:  "",
		D:  "Floating Swarm",
		E:  "Raphaël Bastide; Parsons Paris 18' Students",
		F:  "File Transfer",
		G:  "",
		H:  "",
		I:  "",
		J:  "Raphaël Bastide",
		K:  "",
		L:  "https://floating-swarm.hashbase.io/",
		M:  "",
		N:  "It published the most interesting Parsons Paris student’s net art projects on a decentralized web network.",
		O:  "",
		P:  "Dat is a peer-to-peer network and Beaker Browser allow to surf on it. Beaker makes the publication really easy thanks to a “Create new website” button.",
		Q:  ['./images/73.png']
	},
	color: '#0076c0'
},
{
	type: "艺术家/组合线上项目Artist/Group Online Project",
	year: "2018/6/3",
	name: "1001 Shapes",
	person: "John Provencher",
	info: {
		A: "艺术家/组合线上项目Artist/Group Online Project",
		B:  "2018/6/3",
		C:  "",
		D:  "1001 Shapes",
		E:  "John Provencher",
		F:  "artist website",
		G:  "",
		H:  "",
		I:  "",
		J:  "John Provencher",
		K:  "",
		L:  "https://johnprovencher.com/1001shapes",
		M:  "",
		N:  "",
		O:  "",
		P:  "",
		Q:  ['./images/74.png']
	},
	color: '#3c79bb'
},
{
	type: "Artworks mapped using Machine Learning.",
	year: "2018/3/1",
	name: "t-SNE Map",
	person: "Cyril Diagne, Nicolas Barradeau & Simon Doury",
	info: {
		A: "Artworks mapped using Machine Learning.",
		B:  "2018/3/1",
		C:  "",
		D:  "t-SNE Map",
		E:  "Amit Sood, director of Google's Cultural Institute and Art Project; Google artist in residence Cyril Diagne",
		F:  "Google Arts & Culture",
		G:  "Google Arts & Culture",
		H:  "Google Arts & Culture",
		I:  "Google Arts & Culture",
		J:  "Cyril Diagne, Nicolas Barradeau & Simon Doury",
		K:  "https://www.ted.com/talks/amit_sood_every_piece_of_art_you_ve_ever_wanted_to_see_up_close_and_searchable",
		L:  "https://experiments.withgoogle.com/t-sne-map",
		M:  "谷歌艺术与文化应用",
		N:  "BUILT WITH: t-SNE, Visualization, Data, GLSL, Javascript, TensorFlow, Three.js, WebGL",
		O:  "Artworks mapped using Machine Learning.",
		P:  "All what they have uses  metadata to make connections.  Then, they strip out the metadata, and see what machine learning can do purely based on visual recognition of this entire collection.They ended up with a map that has no reference point information, but has just used visuals to cluster things together, each cluster is art to us. In the cluster of portraits, you can travel through the portraits of the world, also you can do by nature, horses, etc. And they developed the portrait-matcher, so you can upload your selfie to comapre it to the portraits of the world. Actually, it's matching the movement of head!The next experiment is back to machine learning. Since we have visual clusters, what if we ask machine to name these clusters, what if it can tag them, using no actual metadata? Archivist. ",
		Q:  ['./images/75.png']
	},
	color: '#4c7fbd'
},
{
	type: "艺术家/组合线上项目Artist/Group Online Project",
	year: "2018/1/1",
	name: "Laura Swulst Website: Beautiful Company",
	person: "Laurel Schwulst",
	info: {
		A: "艺术家/组合线上项目Artist/Group Online Project",
		B:  "2018/1/1",
		C:  "",
		D:  "Laura Swulst Website: Beautiful Company",
		E:  "Laurel Schwulst",
		F:  "artist website",
		G:  "",
		H:  "",
		I:  "",
		J:  "Laurel Schwulst",
		K:  "https://fruitful.school/",
		L:  "https://beautiful-company.com/",
		M:  "",
		N:  "",
		O:  "",
		P:  "",
		Q:  ['./images/76.png']
	},
	color: '#707cbe'
},
{
	type: "线上档案Digital Archive",
	year: "2018/1/1",
	name: "Open History Archive",
	person: "",
	info: {
		A: "线上档案Digital Archive",
		B:  "2018/1/1",
		C:  "",
		D:  "Open History Archive",
		E:  "",
		F:  "independent website独立网站",
		G:  "",
		H:  "",
		I:  "",
		J:  "",
		K:  "",
		L:  "https://www.openhistoryarchive.com/",
		M:  "",
		N:  "A portal to the History Web. The OPEN HISTORY ARCHIVE gathers, categories and showcases projects that experiment with the World Wide Web as a space for communicating historical knowledge, (mainly) through visual means.",
		O:  "",
		P:  "",
		Q: ['./images/77.png']
	},
	color: '#7f73c1'
},
{
	type: "画廊线上展览Gallery‘s Online Exhibition",
	year: "2017/1/1",
	name: "屏幕间：2020 ART MOMENTS  朋友圈艺博会",
	person: "创始人 周 姜杉 Founder Cedar ZHOU",
	info: {
		A: "画廊线上展览Gallery‘s Online Exhibition",
		B:  "2017/1/1",
		C:  "",
		D:  "屏幕间：2020 ART MOMENTS 朋友圈艺博会",
		E:  "三三子，贺子珂，李维伊，戴丹丹，王⽴⾂、李光",
		F:  "institution's website",
		G:  "屏幕间",
		H:  "",
		I:  "",
		J:  "创始人 周 姜杉 Founder Cedar ZHOU",
		K:  "",
		L:  "https://screenroom.cn",
		M:  "",
		N:  '"屏幕间的策展实践设立了三个主要的研究方向，1）屏幕的沉浸叙事 2）算法环境 3）屏幕作为延伸的空间。屏幕间以展览为单元邀请艺术家与策展人进行策展与展览实践。"',
		O:  "z@screenroom.cn",
		P:  "",
		Q: "",
	},
	color: '#836bc0'
},
{
	type: "线上档案Digital Archive",
	year: "2017/1/1",
	name: "THNGS",
	person: "",
	info: {
		A: "线上档案Digital Archive",
		B:  "2017/1/1",
		C:  "",
		D:  "THNGS",
		E:  "",
		F:  "independent website独立网站",
		G:  "",
		H:  "",
		I:  "",
		J:  "",
		K:  "",
		L:  "https://thngs.co/",
		M:  "",
		N:  "Thngs is a simple tool for the preservation and structuring of data about physical things, a Noah's ark for the tangible world.",
		O:  "",
		P:  "Digital Archive",
		Q: ['./images/79.png'],
	},
	color: '#7c68b0'
},
{
	type: "Fluid Interface, Animated Timeline",
	year: "2017/1/1",
	name: "Free Fall",
	person: "",
	info: {
		A: "Fluid Interface, Animated Timeline",
		B:  "2017/1/1",
		C:  "",
		D:  "Free Fall",
		E:  "Cyril Diagne, Nicolas Barradeau (Google Cultural Institute)",
		F:  "Google Arts & Culture",
		G:  "Google Arts & Culture",
		H:  "Google Arts & Culture",
		I:  "Google Arts & Culture",
		J:  "Cyril Diagne, Nicolas Barradeau (Google Cultural Institute)",
		K:  "https://www.openhistoryarchive.com/free-fall",
		L:  "https://artsexperiments.withgoogle.com/freefall/",
		M:  "",
		N:  "",
		O:  "",
		P:  "Country: United States",
		Q: ['./images/80.png'],
	},
	color: '#81659d'
},
{
	type: "Fluid Interface, Animated Timeline",
	year: "2017/1/1",
	name: "CURATOR TABLE",
	person: "Cyril Diagne, Simon Doury ",
	info: {
		A: "Fluid Interface, Animated Timeline",
		B:  "2017/1/1",
		C:  "",
		D:  "CURATOR TABLE",
		E:  "History of Arts",
		F:  "Google Arts & Culture Lab",
		G:  "Google Arts & Culture Lab",
		H:  "Google Arts & Culture Lab",
		I:  "Google Arts & Culture Lab",
		J:  "Cyril Diagne, Simon Doury",
		K:  "",
		L:  "https://artsexperiments.withgoogle.com/curatortable/",
		M:  "",
		N:  "",
		O:  "",
		P:  "Art History, Design History, History of photography",
		Q:  ['./images/81.png']
	},
	color: '#856567'
},
{
	type: "艺术家作品发布Artist Digital Project",
	year: "2017/1/1",
	name: "White Collar Crime Risk Zones",
	person: "Sam Lavigne",
	info: {
		A: "艺术家作品发布Artist Digital Project",
		B:  "2017/1/1",
		C:  "",
		D:  "White Collar Crime Risk Zones",
		E:  "Sam Lavigne",
		F:  "artist‘s website, mobile app, installation",
		G:  "",
		H:  "",
		I:  "",
		J:  "Sam Lavigne",
		K:  "https://lav.io/",
		L:  "https://whitecollarcrime.zone/",
		M:  "",
		N:  "Usually the crime risk maps used the police system are statistically & institutionallly prejudiced against black people, by showing higher crime rate in black people areas. In this white collar crime risk map, statistically white collar crimes has higher rates in financial centers, which are traditionally white people's gatherings. This map inverts the usual crime risk maps in the police system. ",
		O:  "",
		P:  "",
		Q: ['./images/82.png']
	},
	color: '#965c56'
},
{
	type: "线上档案Digital Archive",
	year: "2016/11/1",
	name: "X Degrees of Separation",
	person: "",
	info: {
		A: "线上档案Digital Archive",
		B:  "2016/11/1",
		C:  "",
		D:  "X Degrees of Separation",
		E:  "History of Arts; Mario Klingemann (Quasimondo)",
		F:  "Google Arts & Culture Lab",
		G:  "Google Arts & Culture Lab",
		H:  "Google Arts & Culture Lab",
		I:  "Google Arts & Culture Lab",
		J:  "",
		K:  "https://twitter.com/quasimondo",
		L:  "https://artsexperiments.withgoogle.com/xdegrees/8gHu5Z5RF4BsNg/BgHD_Fxb-V_K3A",
		M:  "https://showtime.io/Quasimondo",
		N:  "六度分离理论，通过算法寻找图像亲缘关系，在一定的步长下找到两个图像之间的图像相似性",
		O:  "",
		P:  "Germany",
		Q: ['./images/83.png']
	},
	color: '#a4582a'
},
{
	type: "画廊NFT发行Gallery‘s NFT Release",
	year: "2016/4/1",
	name: "uneel cbggre naq gur fbeprere'f fgbar.epub",
	person: "Damon Zucconi",
	info: {
		A: "画廊NFT发行Gallery‘s NFT Release",
		B:  "2016/4/1",
		C:  "",
		D:  "uneel cbggre naq gur fbeprere'f fgbar.epub",
		E:  "Damon Zucconi",
		F:  "epub",
		G:  "Lefty Gallery",
		H:  "Harm van den Dorpel",
		I:  "",
		J:  "Damon Zucconi",
		K:  "https://left.gallery/",
		L:  "https://left.gallery/work/uneel-cbggre-naq-gur-fbepreref-fgbar",
		M:  "",
		N:  "A Caesar cipher is an encryption technique. It is a type of substitution cipher in which each letter in a text is replaced by a letter some fixed number of positions down the alphabet.The method is named after Julius Caesar, who used it in his private correspondence. ",
		O:  "The philosopher's stone is a legendary alchemical substance capable of turning base metals such as mercury into gold or silver.",
		P:  "",
		Q: ['./images/84.jpeg','./images/84-1.png']
	},
	color: '#ae4f03'
},
{
	type: "线上档案Digital Archive",
	year: "2016/1/6",
	name: "Public Domain",
	person: "NYPL",
	info: {
		A: "线上档案Digital Archive",
		B:  "2016/1/6",
		C:  "",
		D:  "Public Domain",
		E:  "NYPL",
		F:  "NYPL",
		G:  "NYPL",
		H:  "",
		I:  "",
		J:  "NYPL",
		K:  "https://www.nypl.org/collections/labs",
		L:  "http://publicdomain.nypl.org/pd-visualization/",
		M:  "",
		N:  "纽约公共图书馆",
		O:  "",
		P:  "",
		Q:  ['./images/85.png']
	},
	color: '#b94624'
},
{
	type: "线上档案Digital Archive",
	year: "2016/1/1",
	name: "Net Art Anthology",
	person: "Mark Beaslez, Senior Front-End Developer; Michael Connor, Artistic Director; Dragan Espenschied,Preservation Director",
	info: {
		A: "线上档案Digital Archive",
		B:  "2016/1/1",
		C:  "2019.6 online",
		D:  "Net Art Anthology",
		E:  "RHIZOME STAFF+ADVISORS (CHAPTERS 1 AND 2)+net artists",
		F:  "ADDITIONAL SUPPORT Google & Google Arts & Culture generously support Rhizome's digital preservation program.",
		G:  "Rhizome",
		H:  "New Museum, winter, 2019, NYC",
		I:  "SITE DESIGN Lukas Eigler-Harding",
		J:  "Mark Beaslez, Senior Front-End Developer; Michael Connor, Artistic Director; Dragan Espenschied,Preservation Director",
		K:  "",
		L:  "https://anthology.rhizome.org/",
		M:  "",
		N:  "CRITERIA The project specifically celebrates works of net art that:Use the net in ways that give expression to emerging subjectivities,Model new forms of collective cultural practice, and/or Exemplify aesthetic, subjective, political, and conceptual positions that have taken on singular and profound resonance within particular networks of artists.Can be meaningfully restaged, reconstructed, or reperformed for this exhibition.",
		O:  "curatorial@rhizome.org",
		P:  "",
		Q:  ['./images/86.png','./images/86-1.png']
	},
	color: '#c33c13'
},
{
	type: "Digital Archive; Online Exhibition",
	year: "2015/3/1",
	name: "Mapping Occupation: Force, Freedom and the Army in Reconstruction",
	person: "Gregory P. Downs and Scott Nesbit",
	info: {
		A: "Digital Archive; Online Exhibition",
		B:  "2015/3/1",
		C:  "",
		D:  "Mapping Occupation: Force, Freedom and the Army in Reconstruction",
		E:  "United States Army; Civil War and through the 1870s; Reconstruction South",
		F:  "",
		G:  "",
		H:  "",
		I:  "",
		J:  "Gregory P. Downs and Scott Nesbit",
		K:  "",
		L:  "https://www.mappingoccupation.org/",
		M:  "",
		N:  "CITATION: Gregory P. Downs and Scott Nesbit, Mapping Occupation: Force, Freedom, and the Army in Reconstruction, http://mappingoccupation.org, published March 2015, accessed (date).",
		O:  "",
		P:  "",
		Q: ['./images/87.png'],
	},
	color: '#ca2d1a'
},
{
	type: "画廊NFT发行Gallery‘s NFT Release",
	year: "2015/1/1",
	name: "Memo: Tokenizing Sustainability",
	person: "Harm van den Dorpel",
	info: {
		A: "画廊NFT发行Gallery‘s NFT Release",
		B:  "2015/1/1",
		C:  "",
		D:  "Memo: Tokenizing Sustainability",
		E:  "Left Gallery",
		F:  "ERC721 smart contract",
		G:  "Left Gallery",
		H:  "",
		I:  "Harm van den Dorpel",
		J:  "",
		K:  "",
		L:  "https://left.gallery/",
		M:  "https://harm.work/news/tokenizing-sustainability",
		N:  "File types computer application screensaver vide ebooks & pdf mobile apps websites merch images animated GIF",
		O:  "content@left.gallery",
		P:  "",
		Q: ['./images/88.png','./images/88-1.png']
	},
	color: '#ca2d38'
},
{
	type: "线上档案Digital Archive",
	year: "2015/1/1",
	name: "Histography",
	person: "Matan Stauber",
	info: {
		A: "线上档案Digital Archive",
		B:  "2015/1/1",
		C:  "",
		D:  "Histography",
		E:  "14 billion years of history, from the Big Bang to 2015",
		F:  "",
		G:  "",
		H:  "",
		I:  "",
		J:  "Matan Stauber",
		K:  "",
		L:  "http://histography.io/",
		M:  "",
		N:  "",
		O:  "",
		P:  "",
		Q: ['./images/89.png']
	},
	color: '#c92367'
},
{
	type: "艺术家平台Artist Stutio/Network",
	year: "2014/11/18",
	name: "Desktop Show",
	person: "Enar de Dios Rodrí­guez",
	info: {
		A: "艺术家平台Artist Stutio/Network",
		B:  "2014/11/18",
		C:  "2014/11/20",
		D:  "Desktop Show",
		E:  "Exhibited artists in Desktop Show: 0100101110101101.org,Kim Asendorf, Eva Beierheimer and Miriam Laussegger, Christophe Bruno, Paolo Cirio, Reynald Drouhin, Oliver Laric, Jan Robert Leegte, Steve or Steven Read, Alexei Shulgin, Eugenio Tisselli, Leonard van Munster",
		F:  "Platform (Conferencing Software) Skype",
		G:  "",
		H:  "",
		I:  "",
		J:  "Enar de Dios Rodrí­guez",
		K:  "",
		L:  "http://www.enardediosrodriguez.com/wp/curatorial/#desktop1",
		M:  "",
		N:  "Desktop Show was an exhibition of net.art works carried out through Skype’s sharing desktop option on November 18-20, 2014. The exhibition took around 20 minutes for each visitor, one visitor at a time.",
		O:  "",
		P:  "",
		Q: ['./images/90.jpeg']
	},
	color: '#d80079'
},
{
	type: "线上档案Digital Archive",
	year: "2013/1/1",
	name: "Past Vision",
	person: "PROJECT LEAD: Dr. Jörg Meiner DESIGN:  Christopher Pietsch",
	info: {
		A: "线上档案Digital Archive",
		B:  "2013/1/1",
		C:  "",
		D:  "Past Vision",
		E:  "Frederick William IV",
		F:  "",
		G:  "Potsdam University of Applied Sciences",
		H:  "Federal Ministry of Education and Research",
		I:  "",
		J:  "PROJECT LEAD: Dr. Jörg Meiner DESIGN:  Christopher Pietsch",
		K:  "",
		L:  "https://uclab.fh-potsdam.de/fw4/",
		M:  "",
		N:  "The visualization shows the inventory of historical drawings by Friedrich Wilhelm IV along a thematic and chronological classification.",
		O:  "",
		P:  "TECHNOLOGY: HTML5, CSS3, Canvas/WebGL, pixi.js and d3.js",
		Q: ['./images/91.png']
	},
	color: '#d20097'
},
{
	type: "Temporary Map; Interactive Documentary",
	year: "2012/6/24",
	name: "Running Reality",
	person: "",
	info: {
		A: "Temporary Map; Interactive Documentary",
		B:  "2012/6/24",
		C:  "",
		D:  "Running Reality",
		E:  "History",
		F:  "独立网站Individual Website",
		G:  "",
		H:  "",
		I:  "",
		J:  "",
		K:  "https://twitter.com/runningreality",
		L:  "https://www.runningreality.org/",
		M:  "",
		N:  "Explore the history of human civilization from 3000BC to today. Running Reality is a world history model with free web and app versions.",
		O:  "",
		P:  "Temporary Map; Interactive Documentary",
		Q: ['./images/92.png']
	},
	color: '#b721cc'
},
{
	type: "艺术家/组合线上项目Artist/Group Online Project",
	year: "2012/1/1",
	name: "Width: 700px;",
	person: "Levi Bruce",
	info: {
		A: "艺术家/组合线上项目Artist/Group Online Project",
		B:  "2012/1/1",
		C:  "",
		D:  "Width: 700px;",
		E:  "Levi Bruce ",
		F:  "Platform (Social Media) Tumblr",
		G:  "",
		H:  "",
		I:  "",
		J:  "Levi Bruce",
		K:  "https://www.curating.online",
		L:  "https://700gallery.tumblr.com/",
		M:  "",
		N:  "The gallery intentionally flattens, reduces, and slows the act of looking at works in a gallery to allow the user to better investigate the works in relation to their presentation online.",
		O:  "",
		P:  "",
		Q: ['./images/93.png']
	},
	color: '#8653c8'
},
{
	type: "线上档案Digital Archive",
	year: "2010/1/1",
	name: "Arts & Culture Experiments-experiment with google collections",
	person: "",
	info: {
		A: "线上档案Digital Archive",
		B:  "2010/1/1",
		C:  "",
		D:  "Arts & Culture Experiments-experiment with google collections",
		E:  "",
		F:  "Google Arts & Culture Lab",
		G:  "Google Arts & Culture Lab",
		H:  "Google Arts & Culture Lab",
		I:  "Google Arts & Culture Lab",
		J:  "Google Arts & Culture Lab",
		K:  "Google Arts & Culture Lab",
		L:  "",
		M:  "https://experiments.withgoogle.com/collection/arts-culture",
		N:  "",
		O:  "Explore a visual chronicle of frontline photojournalist Mo Amin's archive with the help of machine learning.",
		P:  "",
		Q: "",
	},
	color: '#5d63ce'
},
{
	type: "艺术家作品发布Artist Digital Project",
	year: "2009/1/9",
	name: "人民城寨 RMB CITY",
	person: "",
	info: {
		A: "艺术家作品发布Artist Digital Project",
		B:  "2009/1/9",
		C:  "",
		D:  "人民城寨 RMB CITY",
		E:  "曹婓",
		F:  "Platform (game) The Second Life",
		G:  "维他命艺术空间",
		H:  "维他命艺术空间",
		I:  "维他命艺术空间",
		J:  "曹婓",
		K:  "http://vitamincreativespace.art/cn/?work=the-opening-of-rmb-city",
		L:  "http://rmbcity.com/",
		M:  "http://rmbcity.com/2011/01/surf-in-rmb-city/",
		N:  "在不久的将来,中国.翠西计划在Second Life里建设一个主题公园,这里是一个浓缩了几乎所有中国当代城市特征的新城,它是一系列高度自相矛盾的、相互整合的、充满揶揄与质疑的、同时散布极度娱乐和政治意识的新中国画境。",
		O:  "中国当下最热衷的土地开发热情得以继续在Second Life里面迅猛延伸,并且这个”中国”新城在更广阔的全球化数字版图里,它作为一个共产主义、社会主义、资本主义鲁莽的混合体,连同对中国现实符号过剩的挤压,对中国未来粗劣想象,或许我们还能够在辽阔的数字海洋上",
		P:  "看到摩天巨轮旋转在人民英雄纪念碑的顶端,鸟瞰着下方三峡水库急促的水流奔涌出天安门,途经巨型的具新图腾象征的上海电视塔,漫过激流中的飞来寺,越过东北废弃工厂和国家歌剧院的上空,期间偌大的飞机滑过CBD夹缝中的梯田和空中超级商场,水流继续流向珠三角地区货柜码头的巨型马桶,水流回旋于马桶的下水道继而淌进泡着毛泽东塑像的数字海洋,海洋的浪花拍打着奥林匹克”鸟巢”运动场翻腾开来生锈的铁支架,空中乐队在散落开五角星的红旗上响起震耳欲聋的噪音,一再撼动着摇摇欲坠Rem Koolhaas设计的中央电视台……",
		Q: ['./images/95.jpeg']
	},
	color: '#3a6dc0'
},
{
	type: "艺术家平台Artist Stutio/Network",
	year: "2008/1/1",
	name: "Widget Art Gallery",
	person: "Chiara Passa",
	info: {
		A: "艺术家平台Artist Stutio/Network",
		B:  "2008/1/1",
		C:  "",
		D:  "Widget Art Gallery",
		E:  "Chiara Passa",
		F:  "",
		G:  "",
		H:  "",
		I:  "",
		J:  "Chiara Passa",
		K:  "https://www.curating.online",
		L:  "http://www.chiarapassa.it/TheWidgetArtGallery.html",
		M:  "",
		N:  "The Widget Art Gallery (The WAG) is a mini 3-dimensional, single art-gallery room that fits into your pocket.",
		O:  "",
		P:  "",
		Q: ['./images/96.png']
	},
	color: '#0076a3'
},
{
	type: "美术馆线上展 Art Museum Online Exhibition",
	year: "2004/1/1",
	name: "iGalerie",
	person: "",
	info: {
		A: "美术馆线上展 Art Museum Online Exhibition",
		B:  "2004/1/1",
		C:  "",
		D:  "iGalerie",
		E:  "克劳德·克洛斯基（Claude Closky）",
		F:  "美术馆官方网站",
		G:  "卢森堡让大公现代美术馆 Mudam Luxembourg",
		H:  "",
		I:  "",
		J:  "",
		K:  "",
		L:  "",
		M:  "",
		N:  "",
		O:  "",
		P:  "",
		Q: ['./images/97.png']
	},
	color: '#007d7a'
},
{
	type: "线上档案Digital Archive",
	year: "2004/1/1",
	name: "Institute of Network Cultures",
	person: "Geert Lovink",
	info: {
		A: "线上档案Digital Archive",
		B:  "2004/1/1",
		C:  "",
		D:  "Institute of Network Cultures",
		E:  "Geert Lovink",
		F:  "学校官方网站",
		G:  "Amsterdam University of Applied Sciences",
		H:  "",
		I:  "",
		J:  "Geert Lovink",
		K:  "",
		L:  "https://networkcultures.org/",
		M:  "",
		N:  "A key focus is the establishment of sustainable research networks. Emerging critical topics are identified and shaped in a practical sense. Interdisciplinary in character, the INC brings together researchers, artists, activists, programmers, designers, and students and teachers.",
		O:  "",
		P:  "Pay attention to meme studies. Political iconography? ",
		Q: ['./images/98.png']
	},
	color: '#337955'
},
{
	type: "艺术家作品发布Artist Digital Project",
	year: "2003/1/1",
	name: "eGovernment.or.kr",
	person: "Yangachi",
	info: {
		A: "艺术家作品发布Artist Digital Project",
		B:  "2003/1/1",
		C:  "2019/01/01 (remake)",
		D:  "eGovernment.or.kr",
		E:  "Yangachi",
		F:  "artist website",
		G:  "CAC新媒体艺术中心",
		H:  "",
		I:  "",
		J:  "Yangachi",
		K:  "http://www.yangachi.org/?ckattempt=1",
		L:  "http://egovernment.or.kr/",
		M:  "",
		N:  "杰里米·边沁（Jeremy Bentham）于1791年提出了一种圆形全景监狱，但并未被英国政府所采纳。然而，后世的许多其它政府发现了全景概念的迷人之处。因此，全景的规训力量被转化成为了全景主义（Panopticism），即是规训社会的基本原则。全景主义由此拉开了全景世界的帷幕。它由包括身份证、智能卡、闭路电视、快照、五眼系统（美国， 英国， 加拿大， 新西兰以及澳大利亚联合情报系统）、电话窃听、电子指纹、电子健康卡、实名制和韩国教育情报系统（National Education Information System）等多种工具组成。无数的窥视设备在我们不知情的情况下进入了我们的日常生活。因此，我/我们试图以艺术的形式探讨一种反向的全景主义。",
		O:  "",
		P:  "",
		Q: ['./images/99.png']
	},
	color: '#4f7644'
},
{
	type: "线上出版Digital Publishing",
	year: "2002/1/1",
	name: "Runway Journal",
	person: "",
	info: {
		A: "线上出版Digital Publishing",
		B:  "2002/1/1",
		C:  "",
		D:  "Runway Journal",
		E:  "",
		F:  "",
		G:  "artists--run",
		H:  "",
		I:  "",
		J:  "",
		K:  "http://runway.org.au/42archive/",
		L:  "http://runway.org.au/",
		M:  "http://runway.org.au/1-40/29-porn/",
		N:  "Runway Australian Experimental Art is an independent Australian experimental art journal run by a collective of Sydney-based and internationally based artists, writers and Curators.The first issue of the journal was published in 2002 by the Australian artist-run initiative Invisible Inc. Runway was published exclusively in print until it was relaunched at the end of 2013 as an ejournal.(wikipedia)",
		O:  "https://atanazefti.com",
		P:  "AU.Archives are curated spaces. It’s always someone’s responsibility to select what stories or perspectives are collected and represented and these selections can be exclusionary and harmful to different groups of people. ",
		Q: ['./images/100.png']
	},
	color: '#647048'
},
{
	type: "线上档案Digital Archive",
	year: "1996/1/1",
	name: "Internet Archive ",
	person: "",
	info: {
		A: "线上档案Digital Archive",
		B:  "1996/1/1",
		C:  "",
		D:  "Internet Archive ",
		E:  "625 billion web pages 38 million books and texts 14 million audio recordings (including 240,000 live concerts) 7 million videos (including 2 million Television News programs) 4 million images 790,000 software programs",
		F:  "",
		G:  "",
		H:  "",
		I:  "use Wayback Machine",
		J:  "",
		K:  "",
		L:  "https://archive.org/",
		M:  "https://archive.org/help/wayback_api.php",
		N:  "The Internet Archive, a 501(c)(3) non-profit, is building a digital library of Internet sites and other cultural artifacts in digital form. Like a paper library, we provide free access to researchers, historians, scholars, people with print disabilities, and the general public. Our mission is to provide Universal Access to All Knowledge.",
		O:  "We began in 1996 by archiving the Internet itself, a medium that was just beginning to grow in use. Like newspapers, the content published on the web was ephemeral - but unlike newspapers, no one was saving it. Today we have 25+ years of web history accessible through the Wayback Machine and we work with 950+ library and other partners through our Archive-It program to identify important web pages.",
		P:  "️625 BILLION WEB PAGES?? Since 1996?? WAYBACK MACHINE???(PAY ATTENTION!) American Library Association (ALA) sociation for Recorded Sound Collections (ARSC) Biodiversity Heritage Library (BHL) Boston Library Consortium (BLC) Califa Council on Library and Information Resources (CLIR) Coalition for Networked Information (CNI) Digital Library Federation (DLF) Digital Preservation Coalition (DPC) Digital Public Library of America (DPLA) International Federation of Library Associations and Institutions (IFLA) International Internet Preservation Consortium (IIPC) Music Library Association National Digital Stewardship Alliance (NDSA) ReShare",
		Q: ['./images/101.png']
	},
	color: '#726d51'
},
{
	type: "Digital Archive",
	year: "1996/1/1",
	name: "David Rumsey Map Collection: Cartography Associates",
	person: "David Rumsey",
	info: {
		A: "Digital Archive",
		B:  "1996/1/1",
		C:  "",
		D:  "David Rumsey Map Collection: Cartography Associates",
		E:  "United States Army; Reconstructed South",
		F:  "",
		G:  "",
		H:  "",
		I:  "powered by Luna Imaging",
		J:  "David Rumsey",
		K:  "",
		L:  "https://www.davidrumsey.com/",
		M:  "http://www.lunaimaging.com/",
		N:  "The David Rumsey Map Collection was started over 35 years ago and contains more than 150,000 maps. The collection focuses on rare 16th through 21st century maps of North and South America, as well as maps of the World, Asia, Africa, Europe, and Oceania. The collection includes atlases, globes, wall maps, school geographies, pocket maps, books of exploration, maritime charts, and a variety of cartographic materials including pocket, wall, children's, and manuscript maps. Items range in date from around 1550 to the present.",
		O:  "",
		P:  "Digital Archive; Online Exhibition;Digitization of the collection began in 1996 and there are now over 113,000 items online",
		Q: ['./images/102.png']
	},
	color: '#7f6756'
},
{
	type: "画廊线上展览Commercial Gallery‘s Online Exhibition",
	year: "",
	name: "The Flag Art Foundation",
	person: "",
	info: {
		A: "画廊线上展览Commercial Gallery‘s Online Exhibition",
		B:  "",
		C:  "",
		D:  "The Flag Art Foundation",
		E:  "",
		F:  "institution's website",
		G:  "The Flag Art Foundation",
		H:  "",
		I:  "",
		J:  "",
		K:  "",
		L:  "https://flagartfoundation.org/virtual/",
		M:  "",
		N:  "",
		O:  "",
		P:  "",
		Q: "",
	},
	color: '#8c6264'
},
{
	type: "线上档案Digital Archive",
	year: "",
	name: "1917 Free History",
	person: "Mikhail Zygar – project author, founder and editor-in-chief Karen Shainyan – project co-founder and executive director",
	info: {
		A: "线上档案Digital Archive",
		B:  "",
		C:  "",
		D:  "1917 Free History",
		E:  "Mikhail Zygar – project author, founder and editor-in-chief Karen Shainyan – project co-founder and executive director",
		F:  "social media",
		G:  "Pushkin House, London",
		H:  "",
		I:  "",
		J:  "Mikhail Zygar – project author, founder and editor-in-chief Karen Shainyan – project co-founder and executive director",
		K:  "",
		L:  "https://project1917.com/",
		M:  "",
		N:  "“1917. Free History” is a serial, but in the form of a social network. Every day, when you go onto the site, you will find out what happened exactly one hundred years ago",
		O:  "",
		P:  "",
		Q: ['./images/104.png']
	},
	color: '#975a60'
}
]
