list = [{
        order: "",
        keywords: "Game Art",
        year: "",
        title: "",
        url: "",
        author: "",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 1,
        keywords: "Game Art",
        year: "2020年12月22日",
        title: "到美术馆打电子游戏？当代艺术为什么要关注“游戏的人”",
        url: "https://mp.weixin.qq.com/s/evcBE6RL3FENfM6ixj8uqQ",
        author: "何佩莲",
        info: {
            A: "“游戏的人”展",
            B: "策展",
            C: "游戏文化、电子游戏、技术资源、公共游戏空间、陆扬、商业跨界、失败者、郑国谷、曹斐",
            D: "上海",
            E: "明当代美术馆",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 2,
        keywords: "Game Art",
        year: "2020/7/27",
        title: "在世界的游戏中，谁是游戏的人",
        url: "https://mp.weixin.qq.com/s/YxNSIzHoxe86VUXp7yyYeg",
        author: "陈旻",
        info: {
            A: "“游戏社会：狼、猞猁和蚁群”Hyundai Blue Prize 2019年获奖展",
            B: "策展",
            C: "智能终端时代、动物行为、互联网空间、非线性叙事展览、虚拟角色、游戏规则、社会关联、交互场所、集体游戏、共同语言",
            D: "北京",
            E: "现代汽车文化中心",
            F: "陈旻、张业鸿",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 3,
        keywords: "Game Art",
        year: "2020/10/28",
        title: "人机接口——逐渐失控的美丽新世界",
        url: "https://mp.weixin.qq.com/s/V49Uy5K_76l1t0JpKOKKWg",
        author: "",
        info: {
            A: "“人机接口——逐渐失控的美丽新世界”群展",
            B: "策展，新媒体",
            C: "火星、人类、线上展览、虫洞、中央美术学院、游戏式交互体验、非物质性策展",
            D: "线上",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 4,
        keywords: "Game Art",
        year: "2020/3/6",
        title: "属于新世代的线上艺术体验是什么？X美术馆有一个大胆玩法",
        url: "https://mp.weixin.qq.com/s/zlcz2FyiwkJI8ggH8UT5sg",
        author: "",
        info: {
            A: "X美术馆",
            B: "机构",
            C: "线上艺术体验、X美术馆、黄勖夫、交互式虚拟空间、游戏性、强家栋、实体美术馆的延伸、适应新习惯",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 5,
        keywords: "Game Art",
        year: "2020/7/9",
        title: "人工智能艺术 + 游戏艺术 | 龙星如×陈旻×张业鸿",
        url: "https://mp.weixin.qq.com/s/EEZkxQoLOmiIa8jd9g0bFQ",
        author: "龙星如、陈旻、张业鸿",
        info: {
            A: "",
            B: "批评",
            C: "人工智能艺术、游戏艺术、机械、泛智能、机器生命、算法黑箱、科技神话、共同性关系构建、虚拟现实",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 6,
        keywords: "Game Art",
        year: "2020/5/1",
        title: "抗疫消消乐",
        url: "https://mp.weixin.qq.com/s/4jGdAXEXspde_nNsKHjZXA",
        author: "黄一山",
        info: {
            A: "",
            B: "新媒体",
            C: "黄一山、孟尧、消消乐、emoji版权问题、画刊封面计划、游戏制作、互动视频、记忆共享",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 7,
        keywords: "Game Art",
        year: "2020/5/15",
        title: "田晓磊 〈我要为你跳支舞〉",
        url: "https://mp.weixin.qq.com/s/QtRA3rFL_djdlcAlzORAYw",
        author: "王芷子、田晓磊",
        info: {
            A: "林中路｜实验影像工作室",
            B: "新媒体",
            C: "田晓磊、“我要为你跳支舞”、赛伯格形象、VR、虚拟游戏、未来元素品牌",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 8,
        keywords: "Game Art",
        year: "2020/6/18",
        title: "游戏社会的狼、猞猁和蚁群，你想到了社交中的谁？",
        url: "https://mp.weixin.qq.com/s/KVpIJeabfoIsxjxClXqO1w",
        author: "张曦元",
        info: {
            A: "Hyundai Blue Prize 2019获奖展",
            B: "新媒体",
            C: "游戏、陈旻、张业鸿、社交智能、泛智能、狼、信息高速公路、猞猁、原子化、孤独、蚁群、集体协作、疫情",
            D: "北京",
            E: "现代汽车文化中心",
            F: "陈旻、张业鸿",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 9,
        keywords: "Game Art",
        year: "2020/9/27",
        title: "2020亚洲数字艺术展开幕，中国数字艺术大爆发已来临",
        url: "https://mp.weixin.qq.com/s/MjvP7BTlSSMxFT5qWd3Caw",
        author: "任艺时",
        info: {
            A: "亚洲数字艺术展",
            B: "新媒体，策展",
            C: "2020亚洲数字艺术展、亚洲文明对话大会、数字技术、世界处理器、可视化、陈抱阳、展览即游戏、线上展厅",
            D: "北京",
            E: "时代美术馆",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 10,
        keywords: "Game Art",
        year: "2020/6/17",
        title: "当我们遁身游戏世界，看到了什么？",
        url: "https://mp.weixin.qq.com/s/eOfZJaVovyeNCy3izkQ44g",
        author: "龙星如、陆明龙、Dhruv Jani等",
        info: {
            A: "",
            B: "影像",
            C: "陆明龙、数字游戏、超现实主义、虚拟现实、全生产链、叙事能力、游戏媒介语言、引擎技术、历史真实性合法化、游戏逻辑、人工智能、生命科学、生命感",
            D: "北京",
            E: "时代美术馆",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 11,
        keywords: "Game Art",
        year: "2020/10/15",
        title: "CAC Presents | 游戏、数字化人与虚拟偶像",
        url: "https://mp.weixin.qq.com/s/BTOzL2mV4CrHPXQgYP2hEA",
        author: "",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 12,
        keywords: "Game Art",
        year: "2020/11/5",
        title: "无面之眼 I：数字幻想",
        url: "https://mp.weixin.qq.com/s/Dz9C-icSYiMh07_ZQj5EHw",
        author: "",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 13,
        keywords: "Game Art",
        year: "2020/11/6",
        title: "无面之眼 II：新兴现实",
        url: "https://mp.weixin.qq.com/s/AMvK3YX8OsHUvVwaYZfy4w",
        author: "",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 14,
        keywords: "Game Art",
        year: "2020/11/9",
        title: "CAC Presents | 陆扬：妄想世界 + 陸揚地獄",
        url: "https://mp.weixin.qq.com/s/WvZCWbrGHqb0GeBkMTXKkQ",
        author: "",
        info: {
            A: "陆扬：妄想世界（线上表演直播）",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 15,
        keywords: "Game Art",
        year: "2020/8/21",
        title: "郑源 “媒介超忆景观”",
        url: "https://mp.weixin.qq.com/s/ovBP321fKtYA9_YiHo1RKQ",
        author: "郑源、王姝曼",
        info: {
            A: "",
            B: "新媒体",
            C: "郑源、媒介超忆景观、斯诺克、文字、游戏、网络、航空、摄影、连续性、艺术在场性、文化资源",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 16,
        keywords: "Game Art",
        year: "2020/7/10",
        title: "陆扬：我决定舍弃肉身， 重新投胎于虚拟世界",
        url: "https://mp.weixin.qq.com/s/v79KwA-BACDHBiNa8FLC3w",
        author: "上海外滩美术馆、陆扬",
        info: {
            A: "",
            B: "影像",
            C: "陆扬、数字技术、虚拟角色、数字人、面部识别技术、人体改造、真人实时替代系统",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 17,
        keywords: "Game Art",
        year: "2021/1/29",
        title: "文化的涌浪到运筹的回路：边界、区域，及变迁中的劳动",
        url: "https://mp.weixin.qq.com/s/PUk1MtSOGI74gbvNz8zPow",
        author: "Brett Neilson",
        info: {
            A: "Cargonauts, Creative Commons Licence 4.0, 2015",
            B: "新媒体",
            C: "From Flows of Culture to the Circuits of Logistics: borders, regions, labour in transit",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 18,
        keywords: "Game Art",
        year: "2018/1/13",
        title: "最好没有“严肃游戏”",
        url: "https://indienova.com/indie-game-news/its-better-if-there-is-no-serious-game/",
        author: "叶梓涛",
        info: {
            A: "",
            B: "游戏与人文",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 19,
        keywords: "Game Art",
        year: "2018/9/7",
        title: "殊途同归的新媒体艺术与电子游戏",
        url: "https://indienova.com/indie-game-news/its-better-if-there-is-no-serious-game/",
        author: "叶梓涛",
        info: {
            A: "",
            B: "游戏与人文",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 20,
        keywords: "Game Art",
        year: "2018/6/13",
        title: "重思虚拟现实与艺术",
        url: "https://indienova.com/indie-game-news/vr-and-art-rethinking/",
        author: "叶梓涛",
        info: {
            A: "",
            B: "游戏与人文",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 21,
        keywords: "Game Art",
        year: "2020/12/17",
        title: "中国当代艺术场域中的电子游戏｜落日间",
        url: "https://indienova.com/indie-game-news/the-video-game-in-chinese-contemporary-art-field/",
        author: "叶梓涛",
        info: {
            A: "",
            B: "游戏与人文",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 22,
        keywords: "Game Art",
        year: "2019/11/20",
        title: "Ailleurs 别处的游戏设计 第一辑",
        url: "https://indienova.com/indie-game-development/ailleurs-1/",
        author: "叶梓涛",
        info: {
            A: "",
            B: "游戏与人文",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 23,
        keywords: "Game Art",
        year: "2016/8/15",
        title: "叙事的玩法：游戏叙事研究梳理 #1：研究背景",
        url: "https://indienova.com/indie-game-development/game-narrative-1/",
        author: "ayame",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 24,
        keywords: "Game Art",
        year: "2019/8/12",
        title: "游戏研究相关书籍目录",
        url: "https://indienova.com/indie-game-news/personal-game-studies-catalog/",
        author: "叶梓涛",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 25,
        keywords: "Game Art",
        year: "",
        title: "知乎专栏游戏与人文",
        url: "https://zhuanlan.zhihu.com/c_1137656202019459072",
        author: "叶梓涛",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 26,
        keywords: "Game Art",
        year: "2017/9/13",
        title: "游戏理论：哈伦·法罗基（Harun Farocki）最后的项目 | ARTFORUM杂志",
        url: "https://mp.weixin.qq.com/s?__biz=MzA3NjUyNzAxNg==&mid=2649755899&idx=1&sn=cc35cbd9b0e3b6418d80624bf573c764&scene=21",
        author: " Adam Jasper",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: "",
        keywords: "Art Fairs",
        year: "",
        title: "",
        url: "",
        author: "",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 27,
        keywords: "Art Fairs",
        year: "2020/5/30",
        title: "画廊周北京2020，逆境中的重启与复苏",
        url: "https://mp.weixin.qq.com/s/5ZHR-9keyE7GftP74OyOog",
        author: "VIVIAN、王一妃",
        info: {
            A: "画廊周北京",
            B: "博览会",
            C: "画廊周北京2020、活跃行业氛围、最佳展览奖、新势力单元、线下转为线上、挑战与机遇、自媒体宣传、公共单元直播、传媒社会",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 28,
        keywords: "Art Fairs",
        year: "2020/5/1",
        title: "台北当代全新数字计划：要替代的不是一场艺博会！",
        url: "https://mp.weixin.qq.com/s/bekpLIBndqxcD7DrwlOMzg",
        author: "罗书银、岳鸿飞、Christopher Taylor",
        info: {
            A: "台北当代艺博会",
            B: "博览会",
            C: "台北当代、艺术平台Ocula、线上艺博会、99家画廊、免费、疫情",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 29,
        keywords: "Art Fairs",
        year: "2020/3/29",
        title: "滕丽：线上艺博会 更新世界艺术格局的机会？",
        url: "https://mp.weixin.qq.com/s/Bmpi1h5GPKZ4b6hz4D3uKQ",
        author: "罗书银、滕丽",
        info: {
            A: "艺术厦门",
            B: "博览会",
            C: "艺术品线上交易、艺术厦门、线上博览会、推广方式、刚需人群、数据化管理分析、价格公开透明化、艺术市场",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 30,
        keywords: "Art Fairs",
        year: "2020/3/18",
        title: "无奈的新时代？2020香港巴塞尔线上开幕",
        url: "https://mp.weixin.qq.com/s/IkVcIipIPsuk2kKKUs7FpA",
        author: "王家北",
        info: {
            A: "巴塞尔线上",
            B: "博览会",
            C: "香港巴塞尔、线上开幕、巨大作品、摆脱空间限制、现实氛围、身份确认、市场交易、在场、区块链、艺术电商化、终结与再生",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 31,
        keywords: "Art Fairs",
        year: "2020/3/14",
        title: "作品总价值超2.5亿美元，即将开幕的巴塞尔线上展厅有什么值得期待？",
        url: "https://mp.weixin.qq.com/s/0YKvt4_HVqrAUCd8cBex2g",
        author: "Tim Schneider",
        info: {
            A: "巴塞尔线上",
            B: "博览会",
            C: "2.5亿美元、巴塞尔线上展厅、透明度、精确价格",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 32,
        keywords: "Art Fairs",
        year: "2020/3/18",
        title: "线上艺博会的终极提问：会看，但你会买吗？",
        url: "https://mp.weixin.qq.com/s/Hku1HO8cppbWAWPGasBB1w",
        author: "罗书银",
        info: {
            A: "艺术北京、巴塞尔、北京当代",
            B: "博览会，媒介",
            C: "线上艺博会、香港巴塞尔网上展厅、线上交易、艺术品电子商务、消费级艺术品、艺术北京、二级市场成熟遗嘱作品、北京当代、线上线下配合、疫情、实时互动、Zoom Meeting、线上导览、模拟展示图、画廊经营模式革命、潮流艺术",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 33,
        keywords: "Art Fairs",
        year: "2020/3/19",
        title: "巴塞尔首次网上展厅上线，艺博会与画廊寻求线上交易新出路",
        url: "https://mp.weixin.qq.com/s/44QbZOd_GtSTP0bo_fJVWA",
        author: "林佳珣、孟宪晖",
        info: {
            A: "巴塞尔",
            B: "博览会，市场",
            C: "巴塞尔艺术展、网上展厅、线上交易、用户体验、技术限制、自我组织导览、蓝筹画廊、时间限制",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 34,
        keywords: "Art Fairs",
        year: "2020/3/30",
        title: "最全调查！第一个吃螃蟹的线上艺博会战绩如何？",
        url: "https://mp.weixin.qq.com/s/1Mg69XmHSeSrPrTiMiWM6g",
        author: "罗书银",
        info: {
            A: "巴塞尔",
            B: "博览会，市场",
            C: "线上艺博会、首届香港巴塞尔线上展厅、国内画廊差距较大、零成本参展、自身的线上展厅、卓纳画廊“论绘画：线上巴塞尔艺术展”、缓解画廊运营压力、落地展览优势无法取代",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 35,
        keywords: "Art Fairs",
        year: "2020/4/13",
        title: "新秩序的重整，艺术市场在线化的观察",
        url: "https://mp.weixin.qq.com/s/gp_Lkbp48kl8EOwtokRvvA",
        author: "谢盈盈",
        info: {
            A: "",
            B: "市场",
            C: "新秩序、艺术市场在线化、线下无可替代、客户资料",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 36,
        keywords: "Art Fairs",
        year: "2020/7/1",
        title: "下一个收藏热点？新媒体艺术如何买卖？",
        url: "https://mp.weixin.qq.com/s/_IxotLEHqauR8D1hPbQaSw",
        author: "韩晗",
        info: {
            A: "",
            B: "新媒体",
            C: "相对概念、免费获取、艺术品作为应用出售、teamLab、艺术体验、可复制性、无数副本、过时、如何收藏",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: "",
        keywords: "线上策展",
        year: "",
        title: "",
        url: "",
        author: "",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 37,
        keywords: "Online Curation",
        year: "2020/10/9",
        title: "线上策展 第一部分：表现，可变性，物体性",
        url: "https://mp.weixin.qq.com/s/ZSkzV0UW6OebgRsKECK9BA",
        author: "Michael Connor",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 38,
        keywords: "Online Curation",
        year: "2020/8/12",
        title: "探明所有的墙：林云柯谈流媒体平台与线上策展",
        url: "https://mp.weixin.qq.com/s/EK17H2QJ28tl86jPTQZn5g",
        author: "林云柯",
        info: {
            A: "",
            B: "新媒体，策展",
            C: "线上观影、流媒体平台、数字艺术体制、第四堵墙",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 39,
        keywords: "Online Curation",
        year: "2020/4/27",
        title: "身体缺席的艺术：陈嘉莹谈近期的线上艺术展览呈现",
        url: "https://mp.weixin.qq.com/s/mTH-ayp8TIuwgW2U0upcuQ",
        author: "陈嘉莹",
        info: {
            A: "",
            B: "批评",
            C: "陈嘉莹、身体缺席、线上艺术展览、疫情、Bank、网络群展“纯美”、数字通信化、香港巴塞尔、策划语境、自我瓦解、链接的要求、网络艺术、互动式作品、常态、体验经济",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 40,
        keywords: "Online Curation",
        year: "2020/3/19",
        title: "把图片和文字搬到网上就是线上策展吗？",
        url: "https://mp.weixin.qq.com/s/9tvv1vOTswGbmWIdw5niCQ",
        author: "李家丽",
        info: {
            A: "很多",
            B: "策展",
            C: "江苏省美术馆、系列在线展、疫情、陈娅、阿拉里奥画廊、防疫、优势利用、生产反思性话题、策展人身份转换、新媒体规律、内容输出、资本效益、观看体验、300DPI、技术手段、电影导演视角",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 41,
        keywords: "Online Curation",
        year: "2020/4/10",
        title: "不只线上看图，“云看展”如何突破行业壁垒？",
        url: "https://mp.weixin.qq.com/s/uJ-21AlGupQ9eexTmJQTAw",
        author: "郁婷",
        info: {
            A: "昊美术馆的“How Online Exhibition“Google Art&Culture & British Museim Collection Online木木美术馆线上虚拟展览--“艺术还在：一场闭馆期间的展览”“在线公教”",
            B: "机构",
            C: "云看展、VR美术馆Acute Art VR Museum、行业壁垒、知识生产方式、图文看展、类文献、在线数据库、资讯记录手段、视频直播、内容运作、在线公教、云对谈、在线讲座、断线、VR观展、Google Art & Culture、后网络时代",
            D: "本文讨论了疫情影响向全球美术馆“云看展”的不同方式，并关注是否能进行有效观展的同时实现知识生产。",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 42,
        keywords: "Online Curation",
        year: "2020/9/21",
        title: "后疫情时代展览的有效性与无效性互观",
        url: "https://mp.weixin.qq.com/s/iEDZLZafvm7OeJJYPAT8ZQ",
        author: "宋文翔",
        info: {
            A: "",
            B: "批评",
            C: "后疫情时代展览、线上展览、线上的有效性、展场的过度社交化和娱乐化、介入社会问题、应景式时展、抗疫主题展览、审美疲劳、公共秩序",
            D: "本文从策展和展览呈现的角度关注“展览何为”和“何为展览”的问题，讨论了疫情影响下展览的有效和无效性，以及后疫情时代策展所需警惕的问题。",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 43,
        keywords: "Online Curation",
        year: "2020年12月21日",
        title: "当下策展的转向与应对：艺术博物馆的智识机制建构 | “策展在中国”论坛主旨发言",
        url: "https://mp.weixin.qq.com/s/MLAtbpHBikWEl6eBe7y5HQ",
        author: "张子康",
        info: {
            A: "",
            B: "机构，批评",
            C: "艺术博物馆、知识传播中心、大众文化、智识机制建设、线上艺术展、网络依赖性",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 44,
        keywords: "Online Curation",
        year: "2021/2/24",
        title: "Post-2020|当代艺术跃入线上的“数字元年”，正在编码的全球艺术界数字活动地图",
        url: "https://mp.weixin.qq.com/s/Z60-elrBDDBCHpoWN_xZJg",
        author: "",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: "",
        keywords: "History of Digital Art",
        year: "",
        title: "",
        url: "",
        author: "",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 45,
        keywords: "History of Digital Art",
        year: "2020/1/15",
        title: "过去十年，科技如何影响了艺术的模样？",
        url: "https://mp.weixin.qq.com/s/xMzlkhf1Y3bQ3j0-bt0aiA",
        author: "任艺时",
        info: {
            A: "",
            B: "新媒体",
            C: "科技、社交媒体、4G网络、耿雪、蓝牙技术、张鼎、脑科学、神经科学、费俊、冯梦波、语音识别、基因工程、邓悦君、李山",
            D: "本文选取了过去十年科技领域的几项技术突破与产品创新作为切入点，结合对几名艺术家的访谈与对展览机构过去项目，回顾了过去十年“科技与艺术”这一命题的发展情况。",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 46,
        keywords: "History of Digital Art",
        year: "2020/3/11",
        title: "艺术世界被不断推进，科技对艺术作了什么？",
        url: "https://mp.weixin.qq.com/s/os1TDw8IrCqwn4S26EsvkA",
        author: "推 巴塞尔",
        info: {
            A: "",
            B: "新媒体",
            C: "科技、艺术、巴塞尔艺术展50周年、线上展厅、数字艺术、计算机、波普艺术、虚拟现实（VR）、HTC Vive Art、沉浸式、谷歌艺术中心、美感经验",
            D: "本文介绍了科技进步给艺术发展的各个阶段提供的全新形式。",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 47,
        keywords: "History of Digital Art",
        year: "2020/11/8",
        title: "受控随机：数字艺术的早起早期探索",
        url: "https://mp.weixin.qq.com/s/BCq7nMnKhJAQ7UXUDvFeqw",
        author: "",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 48,
        keywords: "History of Digital Art",
        year: "2020年12日7日",
        title: "CAC·阅读 | nettime: 网络艺术（net.art）之起源",
        url: "https://mp.weixin.qq.com/s/yf5t_s-O2rlZ0nLbXxLQqg",
        author: "阿列克谢·舒尔金",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 49,
        keywords: "History of Digital Art",
        year: "1905/7/12",
        title: "We=Link | 早期互联网艺术 I：浏览器艺术与网络艺术美学",
        url: "https://mp.weixin.qq.com/s/euaJ-8287SoxDcfPvbR3Pg",
        author: "",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 50,
        keywords: "History of Digital Art",
        year: "1905/7/12",
        title: "We=Link | 早期网络艺术II：ASCII转码艺术",
        url: "https://mp.weixin.qq.com/s/4hFaZZ5Hj0aWgLZMK5Yz_w",
        author: "",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 51,
        keywords: "History of Digital Art",
        year: "1905/7/12",
        title: "We=Link | 超越编码：文本图形（ASCII Art）术语的批判性观点（上）",
        url: "https://mp.weixin.qq.com/s/T9aFnpZstZR8sLLcTNprJg",
        author: "",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 52,
        keywords: "History of Digital Art",
        year: "1905/7/12",
        title: "We=Link | 超越编码：文本图形（ASCII Art）术语的批判性观点（下）",
        url: "https://mp.weixin.qq.com/s/HV4129_CXi1g4wCh6D-CGA",
        author: "作Anders Carlsson译周蓬岸",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 53,
        keywords: "History of Digital Art",
        year: "1905/7/12",
        title: "We=Link | net.art：网络艺术行动中的那些社群（上）",
        url: "https://mp.weixin.qq.com/s/baENuPpfYZoMhf57245tAg",
        author: "",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 54,
        keywords: "History of Digital Art",
        year: "1905/7/12",
        title: "We=Link | net.art：网络艺术行动中的那些社群（下）",
        url: "https://mp.weixin.qq.com/s/rTJI9xfpaLXzm12VohEsVA",
        author: "",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 55,
        keywords: "History of Digital Art",
        year: "2020/6/20",
        title: "数字时代与公共艺术（二）",
        url: "https://mp.weixin.qq.com/s/Gwoa3enzOfZJN3BUK25aVA",
        author: "张钟萄",
        info: {
            A: "",
            B: "批评、公共艺术",
            C: "公共艺术的永恒性、公私边界模糊、数字公共空间、所有权、私人数据、权力监管、高度弹性的领域结合、数字显示、数字技术",
            D: "本文以数字时代的公共艺术为主题，以数字文化为框架，对数字技术、数字时空以及数字文化框架下的公共艺术及其公共性视角进行了探讨。",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 56,
        keywords: "History of Digital Art",
        year: "1905/7/12",
        title: "We=link | 网络技术与赛博女性主义（上）",
        url: "https://mp.weixin.qq.com/s/QXtk4ZPVuKMfpLdUhAuSqQ",
        author: "",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 57,
        keywords: "History of Digital Art",
        year: "1905/7/12",
        title: "We=link | 网络技术与赛博女性主义（下）",
        url: "https://mp.weixin.qq.com/s/BNTLZsGjKkosX_QvfGwRdw",
        author: "",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 58,
        keywords: "History of Digital Art",
        year: "2020/6/27",
        title: "疫情过后，屏幕将如何影响我们观看艺术的方式？",
        url: "https://mp.weixin.qq.com/s?__biz=MzI3NzUyMTE3NA==&mid=2247498455&idx=1&sn=17763d66cd079f7c0616bdb3c9981bbc&chksm=eb664caedc11c5b8a1e8e84b2f1f778d4fa20d753665b38ea0f2ea8f79ab0dcb8294e13c889c&scene=27",
        author: "",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 59,
        keywords: "History of Digital Art",
        year: "",
        title: "The Transmission of Art by Television",
        url: "https://www.guggenheim.org/blogs/the-take/the-transmission-of-art-by-television",
        author: "",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: "",
        keywords: "Net Art 2020",
        year: "",
        title: "",
        url: "",
        author: "",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 60,
        keywords: "Net Art 2020 2020",
        year: "2020/11/9",
        title: "CAC Presents | 陆扬：妄想世界 + 陸揚地獄",
        url: "https://mp.weixin.qq.com/s/WvZCWbrGHqb0GeBkMTXKkQ",
        author: "",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 61,
        keywords: "Net Art 2020 2020",
        year: "2020/11/11",
        title: "网络艺术，在世界范围恢复和传播",
        url: "https://mp.weixin.qq.com/s/BA-rcwwjnLAbIYIMWcBiHQ",
        author: "Sophie Haigney",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 62,
        keywords: "Net Art 2020 2020",
        year: "1905/7/12",
        title: "疫期对话|e-flux创始人谈互联网艺术史与当下反思",
        url: "https://www.thepaper.cn/newsDetail_forward_7178394?from=singlemessage&isappinstalled=0",
        author: "蔡星洋",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 63,
        keywords: "Net Art 2020 2020",
        year: "2020/12/28",
        title: "CAC · News | ARTnews: 那些定义2020年的作品 —— Get Well Soon!",
        url: "https://mp.weixin.qq.com/s/uvq0V_wWA1-3lv7zwAY8NQ",
        author: "",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 64,
        keywords: "Net Art 2020 2020",
        year: "2020/11/20",
        title: "CAC · 展览 | We=Link：辺 —— 网络平行展正式上线",
        url: "https://mp.weixin.qq.com/s/u_SuvrKrAO9l-RVSnoSe_g",
        author: "",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 65,
        keywords: "Net Art 2020 2020",
        year: "2020/3/15",
        title: "21世纪的第二个十年，艺术市场终于迎来亚洲及数字时代？",
        url: "https://mp.weixin.qq.com/s/YTuHVJiGtwEbDfijPcWvIA",
        author: "佚名",
        info: {
            A: "",
            B: "市场",
            C: "21世纪10年代、亚洲时代、艺术市场、数字时代、线上展厅、打破距离、当代艺术展、销售模式",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 66,
        keywords: "Net Art 2020 2020",
        year: "2020年12月18日",
        title: "虚拟未来：后数字时代的艺术",
        url: "https://mp.weixin.qq.com/s/JU2ZO4Dl5UUnFvYavs9p7A",
        author: "王辛、Jakob Kudsk Steensen",
        info: {
            A: "",
            B: "影像",
            C: "虚拟景观、数字技术、虚拟世界构建、后数字艺术、艺术家自主性、虚拟文化体系、公共艺术领域、数字文化",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 67,
        keywords: "Net Art 2020 2020",
        year: "2020/11/2",
        title: "算法摄影时代的代理政治",
        url: "https://mp.weixin.qq.com/s/RMll0jjSInnPu6-a-oq1ag",
        author: "Hito Steyerl",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 68,
        keywords: "Net Art 2020 2020",
        year: "2020/10/3",
        title: "看不见的图像：人类仍是观看的主体吗？",
        url: "https://mp.weixin.qq.com/s/HUezCn5Mifn6I3ebM-Rbqg",
        author: "Trevor Paglen",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: "",
        keywords: "Screen Media",
        year: "",
        title: "",
        url: "",
        author: "",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 69,
        keywords: "Screen Media",
        year: "2020/6/4",
        title: "《屏幕的强权：当代美术馆的新挑战》",
        url: "https://mp.weixin.qq.com/s/gZuOr8xfzivXc-efu1JTNQ",
        author: "佚名",
        info: {
            A: "",
            B: "机构",
            C: "屏幕、强权、美术馆、流量、线上、知识生产主体、新美术馆学、数据仓库、常态、原作的展示",
            D: "本文讨论屏幕在美术机构中作用的日益重要给美术馆的展览呈现、传播形式、教育项目的开展带来的挑战，以及美术馆人如何应对的议题。",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 70,
        keywords: "Screen Media",
        year: "2020/6/4",
        title: "《屏幕的强权：三个美术馆馆长谈行业新挑战》",
        url: "https://mp.weixin.qq.com/s/YQ3WsSOv_A1KbM8NbHIYow",
        author: "佚名",
        info: {
            A: "",
            B: "机构",
            C: "屏幕、屏幕强权、美术馆线上工作、数据仓库、数字美术馆、数字化交流、艺术体验系统",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 71,
        keywords: "Screen Media",
        year: "2020/7/22",
        title: "从电视艺术到云端屏幕：我们还能相信媒介吗？",
        url: "https://mp.weixin.qq.com/s/3nUiISGwOSDeCYKV_GIAFQ",
        author: "dbk",
        info: {
            A: "",
            B: "新媒体",
            C: "电子屏幕、曹雨、李振华、杨北辰、肖戈、电视艺术、屏幕艺术、录像艺术、媒介生态学、运动影像艺术、扩展电影、前卫艺术、云创作、媒介技术指标、互动参与、在线景观、新社交媒体、尺度、还原现场、全浸式体验",
            D: "本文基于山中天艺术中心开馆展“从屏幕到观念——50年的历史”，分享关于屏幕艺术的论坛讨论，关注媒介的溯源及其生态范围内的多重关系发展。",
            E: "“从屏幕到观念——50年的历史”群展",
            F: "北京",
            G: "山中天艺术中心",
            H: "乔纳斯·斯坦普（Jonas Stampe）、肖戈（策展人访谈）",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 72,
        keywords: "Screen Media",
        year: "2020/6/8",
        title: "我们是屏幕的奴隶吗？ | 屏幕七人谈",
        url: "https://mp.weixin.qq.com/s/HEu-b3xiEWXcLQb7whtAEg",
        author: "佚名",
        info: {
            A: "",
            B: "新媒体",
            C: "屏幕、新媒体艺术、降维、李振华、胡介鸣、aaajiao、郑达、张海超、周姜杉、刘晓都、直播文化、共时、感知、技术、信息流动的媒介、记忆储存方式、权限分配、直播带货、语言学、界面",
            D: "本文通过访谈多位艺术家对于屏幕的认知，展现屏幕在当代艺术界扮演的角色以及我们的应对方式。",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 73,
        keywords: "Screen Media",
        year: "2020年12月18日",
        title: "丁世伟 | 屏幕器官学的意象",
        url: "https://mp.weixin.qq.com/s/7vgoZIEDOPVhJaTLN5NN3A",
        author: "陈旻",
        info: {
            A: "",
            B: "影像",
            C: "“随机预言”丁世伟个展、杭州、想象力学实验室、数字技术、重新构建、数字政治、交互作品、《降维广场》系列、“迷因坍塌”、人机感应系统、“临渊凝视”、信息/数字政治、日常交织、数据场域",
            D: "“随机预言”丁世伟个展",
            E: "杭州",
            F: "想象力学实验室",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 74,
        keywords: "Screen Media",
        year: "2020/7/10",
        title: "鼠标是颗痣？林科FIRE！",
        url: "https://mp.weixin.qq.com/s/VnRZfl1aPnmm_COXVQFoPg",
        author: "佚名",
        info: {
            A: "",
            B: "新媒体",
            C: "林科、屏幕观看角度、黑客帝国、鼠标、痣",
            D: "林科",
            E: "杭州",
            F: "“维度的边界”林科个展",
            G: "浙江美术馆",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 75,
        keywords: "Screen Media",
        year: "1905/7/12",
        title: "媒介考古学：概念与方法 ——西格弗里德·齐林斯基访谈",
        url: "https://mp.weixin.qq.com/s/a_6o941Mmg3_bN4XjTAZ0g",
        author: "唐宏峰；齐林斯基",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: "",
        keywords: "Art Museums",
        year: "",
        title: "",
        url: "",
        author: "",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 76,
        keywords: "Art Museums",
        year: "2020/8/11",
        title: "张子康：疫情之下，实体美术馆何为？",
        url: "https://mp.weixin.qq.com/s/7YBrY8fft0yxfnxLV8cU2A",
        author: "杨钟慧、张子康",
        info: {
            A: "",
            B: "机构",
            C: "公共知识生产、美术馆、数字美术馆、线上展览、艺术教育",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 77,
        keywords: "Art Museums",
        year: "2020年12月21日",
        title: "当下策展的转向与应对：艺术博物馆的智识机制建构 | “策展在中国”论坛主旨发言",
        url: "https://mp.weixin.qq.com/s/MLAtbpHBikWEl6eBe7y5HQ",
        author: "张子康",
        info: {
            A: "",
            B: "机构，批评",
            C: "艺术博物馆、知识传播中心、大众文化、智识机制建设、线上艺术展、网络依赖性",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 78,
        keywords: "Art Museums",
        year: "2020/4/18",
        title: "知己知彼，声击人心：对话秦思源",
        url: "https://mp.weixin.qq.com/s/LGlxlnycFpIp0KcGbyx8GQ",
        author: "Sue Wang、秦思源",
        info: {
            A: "",
            B: "新媒体",
            C: "UCCA×快手“园音”线上音乐会、秦思源、跨文化、“都市发声”、声音总站",
            D: "秦思源",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 79,
        keywords: "Art Museums",
        year: "2020/7/30",
        title: "UCCA馆长田霏宇：最好的计划都被打破后，我们怎么办？",
        url: "https://mp.weixin.qq.com/s/oq-quY5klsQWgwevpNSCgQ",
        author: "刘向林、凡琳、田霏宇",
        info: {
            A: "",
            B: "机构",
            C: "UCCA、良樂、线上音乐会、紧急中的沉思、生存、上海新空间",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: "",
        keywords: "Galleries",
        year: "",
        title: "",
        url: "",
        author: "",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 80,
        keywords: "Galleries",
        year: "2020/4/23",
        title: "最早推出线上展厅的卓纳画廊，又开启了互联网新布局",
        url: "https://mp.weixin.qq.com/s/EXcOfA0qtt9Jso-HMYKxuQ",
        author: "佚名",
        info: {
            A: "卓纳画廊",
            B: "市场",
            C: "卓纳画廊、互联网新布局、数字产品线、工作室、杰作、精准定位一级和二级市场、艺术家新作、经典单幅作品、邀请函、现有藏家独家开放、传统私洽、疫情、平台：纽约项目、中小型画廊、VR应用程序Vortic、全新购买体验、销售工具、线上展厅、价格透明、艺术市场革新",
            D: "本文介绍了卓纳画廊在疫情应对中数字产品线中的两个新项目，以及平台：纽约项目，或可成为未来艺术市场的革新之举。",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 81,
        keywords: "Galleries",
        year: "2020/4/16",
        title: "超级画廊在「云端」",
        url: "https://mp.weixin.qq.com/s/ttL9uMGWYhyViap5fmgiiw",
        author: "凡琳",
        info: {
            A: "",
            B: "机构",
            C: "超级画廊、数字化道路、线上展厅、卓纳画廊、常青画廊、画廊“故事”、豪瑟沃斯画廊、高古轩画廊、里森画廊、厉为阁",
            D: "本文结合具体案例，探讨了国际顶尖画廊在数字化道路上的探索，展现了它们分别都有哪些成功的案列和在疫情期间进行了哪些尝试。并分析了这些行为又预测着一种怎样的未来。",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 82,
        keywords: "Galleries",
        year: "2020/4/13",
        title: "新秩序的重整，艺术市场在线化的观察",
        url: "https://mp.weixin.qq.com/s/gp_Lkbp48kl8EOwtokRvvA",
        author: "谢盈盈",
        info: {
            A: "",
            B: "市场",
            C: "新秩序、艺术市场在线化、线下无可替代、客户资料",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 83,
        keywords: "Galleries",
        year: "2020/3/20",
        title: "艺术界的虚拟时代来临了吗？画廊以云展厅应对疫情危机",
        url: "https://mp.weixin.qq.com/s/O8zon0rbGs0joCX-zLaHsg",
        author: "佚名",
        info: {
            A: "",
            B: "市场",
            C: "香港巴塞尔、线上、云展厅、交易模式、减少货品运输、潜在民主化、展览辅助体验、画廊适应新局面、技术费用压力、线上商店探索、Squarespace",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 84,
        keywords: "Galleries",
        year: "2019/3/30",
        title: "“线上体验”成艺术购买新趋势？画廊巨头高古轩给出答案",
        url: "https://mp.weixin.qq.com/s?__biz=MzI4NTkwMjYyNw==&mid=2247508995&idx=1&sn=ff12449866005d3a263e71a9e51f5e5b&chksm=ebe7f64fdc907f59827d6208f328d3fd3ade2606b6797685a93bcd827999d457b29b24fc0afd&scene=21",
        author: "",
        info: {
            A: "高古轩",
            B: "市场",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 85,
        keywords: "Galleries",
        year: "2020/9/6",
        title: "将体验式艺术打造成产业，佩斯画廊怎么做到的？",
        url: "https://mp.weixin.qq.com/s/iW5yNSDPAPR_PAb6IMsHxw",
        author: "Justin Kamp",
        info: {
            A: "佩斯画廊",
            B: "机构",
            C: "佩斯画廊、体验式艺术、互动性、交互体验、商业模式",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: "",
        keywords: "NGOs",
        year: "",
        title: "",
        url: "",
        author: "",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 86,
        keywords: "NGOs",
        year: "2020年11月17日",
        title: "不同地域当代艺术非营利机构与平台从业者在疫情期的工作实践与反思",
        url: "https://mp.weixin.qq.com/s/JGHvvM8mTvp7tkkJ6_b_kg",
        author: "画廊周北京、吴建儒、刘倩兮等",
        info: {
            A: "",
            B: "机构",
            C: "地域、当代艺术非营利机构、疫情、广东时代美术馆、泛策展、美术馆“实验室”、媒介、政治、公众、线上、泰康空间、Para Site艺术空间、跨地域、上海外滩美术馆、“客堂间”、居委会、社区、美术馆2050、美术馆合作",
            D: "本文介绍不同地域当代艺术非营利机构与平台从业者在疫情期的工作时间与反思，提出美术馆跨平台合作与社区及群体组织建立联系等方案。",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 87,
        keywords: "NGOs",
        year: "2020/4/13",
        title: "寒冬过境 香港画廊面临重新洗牌？",
        url: "https://mp.weixin.qq.com/s/twrzKAtAmiBRvz7qNTxkwg",
        author: "梁侨",
        info: {
            A: "",
            B: "区域，机构",
            C: "香港画廊、社会运动、香港巴塞尔、云展览、卓纳画廊、白石画廊、方由美术、白立方、季丰轩、李安姿当代空间、10号赞善里、世界画廊、明画廊",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 88,
        keywords: "NGOs",
        year: "2020/9/3",
        title: "城市、非城市与非地方：美术馆实践的“社区”转向",
        url: "https://mp.weixin.qq.com/s/CDOhRiL0lPTM4p4NV_QHTw",
        author: "陈晓阳",
        info: {
            A: "",
            B: "批评、机构",
            C: "香港画廊、社会运动、香港巴塞尔、云展览、卓纳画廊、白石画廊、方由美术、白立方、季丰轩、李安姿当代空间、10号赞善里、世界画廊、明画廊",
            D: "社区转向、文化场域、参与式实践项目、公共教育活动、虚拟社区实践",
            E: "本文以几个落地于不同类型社区的美术馆参与式实践项目为线索，从实践者与社群的双向视角来讨论美术馆介入的相关问题。",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 89,
        keywords: "NGOs",
        year: "2020/11/17",
        title: "NOV+| 从城市边缘到zoom会议室，年轻一代的艺术机制实验",
        url: "https://mp.weixin.qq.com/s/hh7EMp8uI28tg2jtZkCIxQ",
        author: "佚名",
        info: {
            A: "",
            B: "新媒体",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 90,
        keywords: "NGOs",
        year: "20201年2月17日",
        title: "SL: 云学术时代的小小平台",
        url: "https://mp.weixin.qq.com/s/b42JviN-AneCBYhHkfGdDA",
        author: "",
        info: {
            A: "www.seminar-live.com",
            B: "学术",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 91,
        keywords: "NGOs",
        year: "2021/2/18",
        title: "《你试过在网店看一场展览吗？ | 拟像线上展览》",
        url: "https://mp.weixin.qq.com/s/-7DtqAT7yw-WGjdmkFYVMQ",
        author: "",
        info: {
            A: "拟像线上展览",
            B: "线上展览",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: "",
        keywords: "Immateriality",
        year: "",
        title: "",
        url: "",
        author: "",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 92,
        keywords: "Immateriality",
        year: "2020/8/18",
        title: "为什么反对在谈“数字化建造”时谈“超物”",
        url: "https://mp.weixin.qq.com/s/IWBBy6Iaw3ciRSDbdlKTZA",
        author: "郑时翔",
        info: {
            A: "",
            B: "批评、新媒体",
            C: "后人文主义建构、超物建造、新概念生成理论、袁烽、数字化建造、赛博格主题、建筑设计、特异性",
            D: "本文探讨了同济大学袁烽老师在数字化建造实践中谈及的后人文主义建构和超物建造概念，在阐释其概念基础的同时，批判性地讨论了数字化建造在当下建筑设计领域的局限性。",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 93,
        keywords: "Immateriality",
        year: "2020/10/13",
        title: " “⾮物质”、“⾮物质 / 再物质”之后再思“物质”",
        url: "https://mp.weixin.qq.com/s/WfdbKaTMK6aDpplyEKbNaw",
        author: "龙星如",
        info: {
            A: "UCCA非物质/再物质",
            B: "新媒体",
            C: "UCCA、“⾮物质 / 再物质”、计算机艺术、新材料与创新力、原生的自己做决定的能力、交互系统、生成艺术、数字物",
            D: "北京",
            E: "UCCA 尤伦斯当代艺术中心",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 94,
        keywords: "Immateriality",
        year: "2020/3/31",
        title: "aaajiao：我们正逐步失去我们线下的身份和形象",
        url: "https://mp.weixin.qq.com/s/00IGoHLuszJGrf23Itki7g",
        author: "龙星如、徐文恺",
        info: {
            A: "",
            B: "新媒体",
            C: "aaajiao、徐文恺、新媒体艺术家、数字化高级玩家、科技工具、失去线下身份、元数据、媒介",
            D: "本文基于aaajiao（徐文恺）的创作脉络与展览线索，分享了徐文恺的新媒体创作观念，及其对数字化媒介的态度。",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: "",
        keywords: "Redefining Exhibition Space",
        year: "",
        title: "",
        url: "",
        author: "",
        info: {
            A: "",
            B: "",
            C: "",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 95,
        keywords: "Redefining Exhibition Space",
        year: "2020/7/4",
        title: "《扩展场域的展览：论中国当代艺术展览的空间转向》",
        url: "https://mp.weixin.qq.com/s/-_BwBFCLCGvfd6-uGdEeBw",
        author: "高远",
        info: {
            A: "",
            B: "批评，机构",
            C: "策展性实践、白立方框架、公众参与性、会化装置、沉浸式、跨机构展陈、跨时代展陈、替代性空间、叠加话语、在地性、跨媒介、艺术乡建、共享体验、展览空间、场域、独立空间、替代性空间",
            D: "本文通过分析近十年来展览空间的发展特点，提出受策展转向的影响，展览空间由白立方拓展出多样形态和文化场域，并改变了作品与空间以及观看体验等多维度的共享关系。",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 96,
        keywords: "Redefining Exhibition Space",
        year: "2020/5/8",
        title: "龙星如谈策展 | 策展是个临时的落脚",
        url: "https://mp.weixin.qq.com/s/DMJWMfx63rTF9s7ZWbyX2A",
        author: "段少锋、龙星如",
        info: {
            A: "",
            B: "策展",
            C: "段少锋、龙星如、艺术与科技、全球性问题、《重思策展：新媒体后的艺术》、空间的“场”和内在叙事",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 97,
        keywords: "Redefining Exhibition Space",
        year: "2020/5/13",
        title: "不能到场的艺术，剩下了什么？",
        url: "https://mp.weixin.qq.com/s/_DdFUY_27J4FoGOZwQGMWw",
        author: "郭成",
        info: {
            A: "",
            B: "批评",
            C: "线上展览、线上直播、社交量化、多频道网络、VR技术、艺术生态转型、艺术市场",
            D: "",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
    {
        order: 98,
        keywords: "Redefining Exhibition Space",
        year: "2020/5/14",
        title: "数字时代与公共艺术（一）",
        url: "https://mp.weixin.qq.com/s/13806GNHGX1BrpprEdRizA",
        author: "张钟萄",
        info: {
            A: "",
            B: "新媒体、公共",
            C: "数字时代、数字文化、数字技术、工业革命、电脑艺术、数字时空、公共空间、公共领域",
            D: "本文以数字时代的公共艺术为主题，以数字文化为框架，对数字技术、数字时空以及数字文化框架下的公共艺术进行了探讨。",
            E: "",
            F: "",
            G: "",
            H: "",
            I: "",
            J: "",
            K: "",
            L: "",
            M: "",
            N: "",
            O: "",
            P: "",
        },
    },
];